-- 00036_seed_gc_contacts_batch3.sql
-- Seed batch 3: 9 MI GC companies + 63 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone left null (NOT NULL constraint — use company main line).

-- ============================================================
-- COMPANIES
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Sachse Construction', 'GC', 'MI', 'Detroit, MI', '(313) 481-8200', 'Detroit', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Sachse Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Wolverine Building Group', 'GC', 'MI', 'Grand Rapids, MI', '(616) 949-3360', 'Grand Rapids', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Wolverine Building Group');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Wolgast Corporation', 'GC', 'MI', 'Saginaw, MI', '(989) 790-9120', 'Saginaw', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Wolgast Corporation');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'J.S. Vig Construction', 'GC', 'MI', 'Plymouth, MI', '(734) 283-3002', 'Plymouth', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'J.S. Vig Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Roncelli', 'GC', 'MI', 'Sterling Heights, MI', '(586) 264-2060', 'Sterling Heights', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Roncelli');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Jarbou Ronnisch Construction', 'GC', 'MI', 'Royal Oak, MI', '(248) 549-1800', 'Royal Oak', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Jarbou Ronnisch Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Clark Construction Company', 'GC', 'MI', 'Lansing, MI', '(517) 372-0940', 'Lansing', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Clark Construction Company');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Oliver / Hatcher Construction', 'GC', 'MI', 'Novi, MI', '(248) 374-1100', 'Novi', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Oliver / Hatcher Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'AUCH Construction', 'GC', 'MI', 'Pontiac, MI', '(248) 334-2000', 'Pontiac', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'AUCH Construction');

-- ============================================================
-- CONTACTS (63)
-- ============================================================

-- Sachse Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Mark Andonian', c.id, 'ESTIMATOR', '(313) 481-8200', 'Senior Preconstruction Manager', false, 'https://www.linkedin.com/in/mark-andonian-7a99858a/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Andonian' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Brad Miller', c.id, 'ESTIMATOR', '(313) 481-8200', 'Senior Pre-Construction Manager', false, 'https://www.linkedin.com/in/brad-miller-685745129/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brad Miller' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Rick Stanza', c.id, 'ESTIMATOR', '(313) 481-8200', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/rick-stanza-21953267/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rick Stanza' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Mike Eberhardt', c.id, 'ESTIMATOR', '(313) 481-8200', 'Preconstruction Manager - Commercial Group', false, 'https://www.linkedin.com/in/mikeeberhardt/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Eberhardt' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Antoinette Miller', c.id, 'ESTIMATOR', '(313) 481-8200', 'Estimator', false, 'https://www.linkedin.com/in/antoinette-miller-864802128/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Antoinette Miller' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Amogh Doijad', c.id, 'ESTIMATOR', '(313) 481-8200', 'Cost Engineer (Cost & Procurement)', false, 'https://www.linkedin.com/in/amogh-doijad-4582a9143/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Amogh Doijad' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Terman', c.id, 'PM', '(313) 481-8200', 'Senior Project Manager', false, 'https://www.linkedin.com/in/matt-terman-3380357/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Terman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Tony Ciciretto', c.id, 'PM', '(313) 481-8200', 'Senior Project Manager', false, 'https://www.linkedin.com/in/tony-ciciretto-leed-ap/' FROM companies c WHERE c.name='Sachse Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tony Ciciretto' AND company_id=c.id);

-- Wolverine Building Group (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Randy Baker', c.id, 'ESTIMATOR', '(616) 949-3360', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/randy-baker-633a461a/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Randy Baker' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Heitz', c.id, 'ESTIMATOR', '(616) 949-3360', 'Project Estimator', false, 'https://www.linkedin.com/in/matt-heitz-1b914449/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Heitz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Daniel Zilzer', c.id, 'PM', '(616) 949-3360', 'Senior Project Manager', false, 'https://www.linkedin.com/in/daniel-zilzer-93382aa9/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Zilzer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Bryan Richardson', c.id, 'PM', '(616) 949-3360', 'Senior Project Manager', false, 'https://www.linkedin.com/in/bryan-richardson-b8bb7ab/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bryan Richardson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Cyrus Brandenburg', c.id, 'PM', '(616) 949-3360', 'Senior Project Manager', false, 'https://www.linkedin.com/in/cyrus-brandenburg-7825348/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Cyrus Brandenburg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jonathan Reimink', c.id, 'PM', '(616) 949-3360', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jonathan-reimink-pe-0732467a/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jonathan Reimink' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'John Lafrinere', c.id, 'PM', '(616) 949-3360', 'Senior Project Manager', false, 'https://www.linkedin.com/in/john-lafrinere-231a204b/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Lafrinere' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'David Paquet', c.id, 'PM', '(616) 949-3360', 'Project Manager', false, 'https://www.linkedin.com/in/david-paquet-83364a91/' FROM companies c WHERE c.name='Wolverine Building Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Paquet' AND company_id=c.id);

-- Wolgast Corporation (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Eric Schwartzly', c.id, 'PM', '(989) 790-9120', 'Director of Restaurant Construction', true, 'https://www.linkedin.com/in/eric-schwartzly-87849a18/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Schwartzly' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Joshua Lakie', c.id, 'ESTIMATOR', '(989) 790-9120', 'Project Estimator', false, 'https://www.linkedin.com/in/joshua-lakie-90161b80/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joshua Lakie' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Amber Swanson', c.id, 'ESTIMATOR', '(989) 790-9120', 'Estimator Assistant', false, 'https://www.linkedin.com/in/amber-swanson-134a5982/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Amber Swanson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jim Venton', c.id, 'PM', '(989) 790-9120', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jim-venton-b74868b3/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Venton' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Greg Stadler', c.id, 'PM', '(989) 790-9120', 'Project Manager', false, 'https://www.linkedin.com/in/greg-stadler-9ba55367/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Greg Stadler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Vince Drumright', c.id, 'PM', '(989) 790-9120', 'Project Manager', false, 'https://www.linkedin.com/in/vince-drumright-48774676/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Vince Drumright' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Craig Myers', c.id, 'PM', '(989) 790-9120', 'Project Manager', false, 'https://www.linkedin.com/in/craig-myers-b224491a/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Craig Myers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Justin Schroeder', c.id, 'PM', '(989) 790-9120', 'Project Manager', false, 'https://www.linkedin.com/in/justin-schroeder-0760a71b1/' FROM companies c WHERE c.name='Wolgast Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Schroeder' AND company_id=c.id);

-- J.S. Vig Construction (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Brett Levko', c.id, 'ESTIMATOR', '(734) 283-3002', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/brettjlevko/' FROM companies c WHERE c.name='J.S. Vig Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brett Levko' AND company_id=c.id);

-- Roncelli (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jim Carnacchi', c.id, 'ESTIMATOR', '(586) 264-2060', 'Chief Preconstruction Officer', true, 'https://www.linkedin.com/in/jim-carnacchi-626673b/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Carnacchi' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Bill Palazzolo', c.id, 'ESTIMATOR', '(586) 264-2060', 'Director of Preconstruction (Specialized Markets)', true, 'https://www.linkedin.com/in/bill-palazzolo-71856862/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bill Palazzolo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Steven Holtcamp', c.id, 'ESTIMATOR', '(586) 264-2060', 'Lead Estimator', false, 'https://www.linkedin.com/in/steven-holtcamp-830862121/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Holtcamp' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Ted Shekell', c.id, 'ESTIMATOR', '(586) 264-2060', 'Sr. Estimator / Project Manager - Self Perform Group', false, 'https://www.linkedin.com/in/ted-shekell-8944421a/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ted Shekell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Herbon', c.id, 'PM', '(586) 264-2060', 'Senior Project Manager', false, 'https://www.linkedin.com/in/michael-herbon-pe-3355bb16/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Herbon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Christian Contarino', c.id, 'PM', '(586) 264-2060', 'Senior Project Manager', false, 'https://www.linkedin.com/in/christian-contarino-b29b9a115/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christian Contarino' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Justin Bott', c.id, 'PM', '(586) 264-2060', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/justinbott/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Bott' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Mellen', c.id, 'PM', '(586) 264-2060', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/matt-mellen-60635a1b/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Mellen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jay Thomas', c.id, 'PM', '(586) 264-2060', 'Project Manager', false, 'https://www.linkedin.com/in/jay-thomas-a2755141/' FROM companies c WHERE c.name='Roncelli' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jay Thomas' AND company_id=c.id);

-- Jarbou Ronnisch Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Phillips', c.id, 'ESTIMATOR', '(248) 549-1800', 'Chief Estimator', true, 'https://www.linkedin.com/in/michael-phillips-89689b16/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Phillips' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Hunter Taylor', c.id, 'ESTIMATOR', '(248) 549-1800', 'Estimator', false, 'https://www.linkedin.com/in/htaylor68/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Hunter Taylor' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'David Dourjalian', c.id, 'ESTIMATOR', '(248) 549-1800', 'Construction Estimator', false, 'https://www.linkedin.com/in/david-dourjalian-885a569b/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Dourjalian' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Garrett Dulecki', c.id, 'ESTIMATOR', '(248) 549-1800', 'Construction Estimator', false, 'https://www.linkedin.com/in/garrett-dulecki-a16a28186/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Garrett Dulecki' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Richard Polan', c.id, 'PM', '(248) 549-1800', 'Project Director', true, 'https://www.linkedin.com/in/rickpolan/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Polan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Andrew Di Dio', c.id, 'PM', '(248) 549-1800', 'Senior Project Manager', false, 'https://www.linkedin.com/in/andrew-di-dio-cm-lean-31b14859/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Di Dio' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Tyler Gabor', c.id, 'PM', '(248) 549-1800', 'Project Manager', false, 'https://www.linkedin.com/in/tyler-gabor-3a2470170/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Gabor' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Armen Derderian', c.id, 'PM', '(248) 549-1800', 'Project Manager', false, 'https://www.linkedin.com/in/armen-derderian-25943193/' FROM companies c WHERE c.name='Jarbou Ronnisch Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Armen Derderian' AND company_id=c.id);

-- Clark Construction Company (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Bud Provenzano', c.id, 'ESTIMATOR', '(517) 372-0940', 'Sr. Estimator', false, 'https://www.linkedin.com/in/bud-provenzano-967a7015/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bud Provenzano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Andrew Bourgois', c.id, 'ESTIMATOR', '(517) 372-0940', 'Senior MEP Estimator', false, 'https://www.linkedin.com/in/andy-bourgois-5b5a5232/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Bourgois' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Allison Clark', c.id, 'ESTIMATOR', '(517) 372-0940', 'PreCon Project Leader', false, 'https://www.linkedin.com/in/allison-clark-52a90635/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Allison Clark' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Chad Thelen', c.id, 'PM', '(517) 372-0940', 'Senior Project Manager - Market Leader', false, 'https://www.linkedin.com/in/chad-thelen-82abb157/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chad Thelen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Wielechowski', c.id, 'PM', '(517) 372-0940', 'Senior Project Manager', false, 'https://www.linkedin.com/in/matt-wielechowski-49434512/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Wielechowski' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Chris Martin', c.id, 'PM', '(517) 372-0940', 'Senior Project Manager - Market Leader', false, 'https://www.linkedin.com/in/chris-martin-92041918/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Martin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Ryan Wenzel', c.id, 'PM', '(517) 372-0940', 'Project Manager', false, 'https://www.linkedin.com/in/ryanswenzel/' FROM companies c WHERE c.name='Clark Construction Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Wenzel' AND company_id=c.id);

-- Oliver / Hatcher Construction (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Christian Laycock', c.id, 'ESTIMATOR', '(248) 374-1100', 'Chief Estimator', true, 'https://www.linkedin.com/in/christian-laycock-b761541/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christian Laycock' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Schumacher', c.id, 'ESTIMATOR', '(248) 374-1100', 'Senior Project Estimator', false, 'https://www.linkedin.com/in/michael-schumacher-pe-6656569/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Schumacher' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Pooja Patil', c.id, 'ESTIMATOR', '(248) 374-1100', 'Senior Estimator', false, 'https://www.linkedin.com/in/pooja-patil-51167979/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pooja Patil' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jennifer Rose', c.id, 'PM', '(248) 374-1100', 'Senior Project & Pre-Construction Manager', false, 'https://www.linkedin.com/in/jennifer-rose-592425/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jennifer Rose' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Derek Dobias', c.id, 'PM', '(248) 374-1100', 'Project Manager', false, 'https://www.linkedin.com/in/derek-dobias-oliver-hatcher-construction/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Derek Dobias' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Dan O''Donnell', c.id, 'PM', '(248) 374-1100', 'Senior Project Manager & Registered Architect', false, 'https://www.linkedin.com/in/dan-o-donnell-b677666/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dan O''Donnell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'John Ruttkofsky', c.id, 'PM', '(248) 374-1100', 'Project Director', true, 'https://www.linkedin.com/in/john-ruttkofsky-7b239513b/' FROM companies c WHERE c.name='Oliver / Hatcher Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Ruttkofsky' AND company_id=c.id);

-- AUCH Construction (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Gerry McClelland', c.id, 'ESTIMATOR', '(248) 334-2000', 'Director of Preconstruction Services', true, 'https://www.linkedin.com/in/gerry-mcclelland-cpe-b1863021/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Gerry McClelland' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matthew Wiemer', c.id, 'ESTIMATOR', '(248) 334-2000', 'Senior Estimator', false, 'https://www.linkedin.com/in/matthew-wiemer-99208322/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Wiemer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Robert Berryman', c.id, 'ESTIMATOR', '(248) 334-2000', 'Construction Estimator', false, 'https://www.linkedin.com/in/robert-berryman-02550325/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Berryman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jim Chernosky', c.id, 'PM', '(248) 334-2000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jim-chernosky-70938825/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Chernosky' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Scott Oswald', c.id, 'PM', '(248) 334-2000', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/scott-oswald-6456663/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Oswald' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'M. Tyler Maki', c.id, 'PM', '(248) 334-2000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/m-tyler-maki-626b7837/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='M. Tyler Maki' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Aaron St. Dennis', c.id, 'PM', '(248) 334-2000', 'Project Manager', false, 'https://www.linkedin.com/in/aaron-st-dennis-cdt-cm-bim-11646911/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Aaron St. Dennis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jacob Munchiando', c.id, 'PM', '(248) 334-2000', 'Project Director', true, 'https://www.linkedin.com/in/jacob-munchiando-93b43282/' FROM companies c WHERE c.name='AUCH Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Munchiando' AND company_id=c.id);
