-- 00039_seed_il_gc_contacts.sql
-- Seed IL GCs: 4 companies + 26 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint).

-- ============================================================
-- COMPANIES (with website)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Englewood Construction', 'GC', 'IL', 'Lemont, IL', '(847) 233-9200', 'https://www.englewoodconstruction.com', 'Lemont', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Englewood Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Leopardo Construction', 'GC', 'IL', 'Hoffman Estates, IL', '(847) 783-3000', 'https://leopardo.com', 'Hoffman Estates', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Leopardo Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Novak Construction', 'GC', 'IL', 'Chicago, IL', '(773) 278-1100', 'https://www.novakconstruction.com', 'Chicago', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Novak Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Pepper Construction', 'GC', 'IL', 'Chicago, IL', '(312) 266-4700', 'https://www.pepperconstruction.com', 'Chicago', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Pepper Construction');

-- ============================================================
-- CONTACTS (26)
-- ============================================================

-- Englewood Construction (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tara Fox', c.id, 'PM', '(847) 233-9200', 'Director of Construction', true, 'https://www.linkedin.com/in/tarafox/', 'Lemont', 'IL' FROM companies c WHERE c.name='Englewood Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tara Fox' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Dave Palansky', c.id, 'PM', '(847) 233-9200', 'Director of Construction', true, 'https://www.linkedin.com/in/dave-palansky-a809071b/' FROM companies c WHERE c.name='Englewood Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dave Palansky' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ron Koepl', c.id, 'SUPER', '(847) 233-9200', 'Project Manager / Superintendent', false, 'https://www.linkedin.com/in/ron-koepl-3b0b34aa/', 'Dyer', 'IN' FROM companies c WHERE c.name='Englewood Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ron Koepl' AND company_id=c.id);

-- Leopardo Construction (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matt Pederson', c.id, 'ESTIMATOR', '(847) 783-3000', 'Senior Preconstruction Manager', false, 'https://www.linkedin.com/in/matt-pederson-39172b4a/', 'Algonquin', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Pederson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jeff Montanari', c.id, 'PM', '(847) 783-3000', 'Project Executive', true, 'https://www.linkedin.com/in/jeff-montanari-01b5aa71/', 'Chicago', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jeff Montanari' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Utah', c.id, 'PM', '(847) 783-3000', 'Project Executive', true, 'https://www.linkedin.com/in/jason-utah-chc-0a41611a/', 'Chicago', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Utah' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Camille T.', c.id, 'PM', '(847) 783-3000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/camille-t-21b84912/', 'Hoffman Estates', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Camille T.' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Sean Scott', c.id, 'PM', '(847) 783-3000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/sean-scott-153ab471/', 'Crystal Lake', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sean Scott' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jacob Wedemeier', c.id, 'PM', '(847) 783-3000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jacob-wedemeier-a8b18784/', 'Chicago', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Wedemeier' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jack Leopardo', c.id, 'PM', '(847) 783-3000', 'Project Manager II', false, 'https://www.linkedin.com/in/jack-leopardo-60a72713a/', 'Chicago', 'IL' FROM companies c WHERE c.name='Leopardo Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jack Leopardo' AND company_id=c.id);

-- Novak Construction (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Determann', c.id, 'ESTIMATOR', '(773) 278-1100', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/john-determann-4813b211/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Determann' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jaipreet Raina', c.id, 'ESTIMATOR', '(773) 278-1100', 'Estimator', false, 'https://www.linkedin.com/in/jaipreet-raina/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jaipreet Raina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Thomas DeMoss', c.id, 'ESTIMATOR', '(773) 278-1100', 'Estimator', false, 'https://www.linkedin.com/in/thomas-demoss-0a2551141/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Thomas DeMoss' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Randy Coakley', c.id, 'PM', '(773) 278-1100', 'Project Director', true, 'https://www.linkedin.com/in/randy-coakley-7136553/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Randy Coakley' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jim Hempleman', c.id, 'PM', '(773) 278-1100', 'Project Director', true, 'https://www.linkedin.com/in/jim-hempleman-1a809094/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Hempleman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Robbie Stangle', c.id, 'PM', '(773) 278-1100', 'Senior Project Manager', false, 'https://www.linkedin.com/in/robbie-stangle-b15a8b82/', 'Carol Stream', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robbie Stangle' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ryan Powell', c.id, 'PM', '(773) 278-1100', 'Senior Project Manager', false, 'https://www.linkedin.com/in/ryan-powell-3b859757/', 'Mount Prospect', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Powell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Alan Sheehan', c.id, 'PM', '(773) 278-1100', 'Senior Project Manager', false, 'https://www.linkedin.com/in/alan-sheehan-27407150/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alan Sheehan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Michael Lestina', c.id, 'PM', '(773) 278-1100', 'Project Manager', false, 'https://www.linkedin.com/in/michael-lestina-0b955776/', 'Palatine', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Lestina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kevin Thieme', c.id, 'PM', '(773) 278-1100', 'Project Manager', false, 'https://www.linkedin.com/in/kevin-thieme-90610b23/', 'Chicago', 'IL' FROM companies c WHERE c.name='Novak Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kevin Thieme' AND company_id=c.id);

-- Pepper Construction (6)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'James Kapp', c.id, 'PM', '(312) 266-4700', 'Project Executive', true, 'https://www.linkedin.com/in/james-kapp-970b02107/', 'Chicago', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='James Kapp' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Juanita Garcia', c.id, 'PM', '(312) 266-4700', 'Project Executive - High Performance & Sustainable', true, 'https://www.linkedin.com/in/juanitagarcia/', 'Chicago', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Juanita Garcia' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dan Rosenberg', c.id, 'PM', '(312) 266-4700', 'Project Executive', true, 'https://www.linkedin.com/in/dan-rosenberg-054abb18/', 'Des Plaines', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dan Rosenberg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kenneth Russell', c.id, 'PM', '(312) 266-4700', 'Project Director / Director of Mission Critical', true, 'https://www.linkedin.com/in/kenneth-russell-35687026/', 'Palatine', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kenneth Russell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nate Chase', c.id, 'PM', '(312) 266-4700', 'Project Manager II', false, 'https://www.linkedin.com/in/nate-chase-947620199/', 'Chicago', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nate Chase' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Joe Gallo', c.id, 'PM', '(312) 266-4700', 'Project Manager II', false, 'https://www.linkedin.com/in/joe-gallo-bb1935139/', 'Chicago', 'IL' FROM companies c WHERE c.name='Pepper Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joe Gallo' AND company_id=c.id);
