-- 00037_seed_gc_contacts_batch4.sql
-- Seed batch 4: 7 OH GC companies + 49 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint; individual phones unknown).

-- ============================================================
-- COMPANIES
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Construction One', 'GC', 'OH', 'Columbus, OH', '(614) 235-0057', 'Columbus', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Construction One');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Cleveland Construction, Inc.', 'GC', 'OH', 'Mentor, OH', '(440) 255-8000', 'Mentor', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Cleveland Construction, Inc.');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Panzica Construction', 'GC', 'OH', 'Mayfield Village, OH', '(440) 442-4300', 'Mayfield Village', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Panzica Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Ruscilli Construction', 'GC', 'OH', 'Dublin, OH', '(614) 876-9484', 'Dublin', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Ruscilli Construction');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Elford, Inc.', 'GC', 'OH', 'Columbus, OH', '(614) 488-4000', 'Columbus', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Elford, Inc.');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Setterlin Building Company', 'GC', 'OH', 'Columbus, OH', '(614) 459-7077', 'Columbus', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Setterlin Building Company');
INSERT INTO companies (name, type, region, address, phone, city, state) SELECT 'Skoda Construction Inc.', 'GC', 'OH', 'Cleveland, OH', '(216) 214-3142', 'Cleveland', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Skoda Construction Inc.');

-- ============================================================
-- CONTACTS (49)
-- ============================================================

-- Construction One (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Bob Dech', c.id, 'ESTIMATOR', '(614) 235-0057', 'Sr. Estimator', false, 'https://www.linkedin.com/in/bobdech/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bob Dech' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Sadie Salerno', c.id, 'ESTIMATOR', '(614) 235-0057', 'Construction Estimator', false, 'https://www.linkedin.com/in/sadie-salerno-9b7a20a/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sadie Salerno' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Este Moraleja', c.id, 'ESTIMATOR', '(614) 235-0057', 'Estimator', false, 'https://www.linkedin.com/in/este-moraleja-29908445/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Este Moraleja' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Travis Weed', c.id, 'ESTIMATOR', '(614) 235-0057', 'Estimator', false, 'https://www.linkedin.com/in/travis-weed-5a265750/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Travis Weed' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Mark Shy', c.id, 'ESTIMATOR', '(614) 235-0057', 'Preconstruction / Business Development - Ohio Region', false, 'https://www.linkedin.com/in/markshy/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Shy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Erich Harshbarger', c.id, 'PM', '(614) 235-0057', 'Director of Construction Services', true, 'https://www.linkedin.com/in/erich-harshbarger-b8018b21/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Erich Harshbarger' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jacob Krum', c.id, 'PM', '(614) 235-0057', 'Director of Construction', true, 'https://www.linkedin.com/in/jacob-krum-45b95869/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Krum' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Mark Quisenberry', c.id, 'PM', '(614) 235-0057', 'Project Manager', false, 'https://www.linkedin.com/in/mark-quisenberry-baab08a/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Quisenberry' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Patrick Corbett', c.id, 'PM', '(614) 235-0057', 'Project Manager', false, 'https://www.linkedin.com/in/patrick-corbett-b3015494/' FROM companies c WHERE c.name='Construction One' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Patrick Corbett' AND company_id=c.id);

-- Cleveland Construction, Inc. (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Randy Stoops', c.id, 'ESTIMATOR', '(440) 255-8000', 'Chief Estimator', true, 'https://www.linkedin.com/in/randy-stoops-367a8493/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Randy Stoops' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Clint McCurdy', c.id, 'ESTIMATOR', '(440) 255-8000', 'Senior Estimator', false, 'https://www.linkedin.com/in/clint-j-mccurdy-9a147a78/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Clint McCurdy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Philip Kristoff', c.id, 'ESTIMATOR', '(440) 255-8000', 'Estimator', false, 'https://www.linkedin.com/in/kristoff-philip/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Philip Kristoff' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Mike Ugrinic', c.id, 'ESTIMATOR', '(440) 255-8000', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/mikeugrinic/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Ugrinic' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Ray Kriz', c.id, 'PM', '(440) 255-8000', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/ray-kriz-bbb7b9340/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ray Kriz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Onslow', c.id, 'PM', '(440) 255-8000', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/matt-onslow-49693819/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Onslow' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Seth Daniels', c.id, 'PM', '(440) 255-8000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/gdsuhdsj4420534/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Seth Daniels' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'David Allchin', c.id, 'PM', '(440) 255-8000', 'Project Manager', false, 'https://www.linkedin.com/in/david-allchin-431835161/' FROM companies c WHERE c.name='Cleveland Construction, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Allchin' AND company_id=c.id);

-- Panzica Construction (6)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Ryan Hamilton', c.id, 'ESTIMATOR', '(440) 442-4300', 'Estimator', false, 'https://www.linkedin.com/in/ryan-hamilton-846779141/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Hamilton' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Bill O''Hare', c.id, 'PM', '(440) 442-4300', 'Senior Project Manager', false, 'https://www.linkedin.com/in/bill-o-hare-bb940820/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bill O''Hare' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Steve Nock', c.id, 'PM', '(440) 442-4300', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/steve-nock-92a64865/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steve Nock' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Patrick Conochan', c.id, 'PM', '(440) 442-4300', 'Project Manager', false, 'https://www.linkedin.com/in/patrick-conochan-23915730/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Patrick Conochan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Gerald Federan', c.id, 'PM', '(440) 442-4300', 'Project Manager', false, 'https://www.linkedin.com/in/gerald-federan-536399147/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Gerald Federan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Ashley Lanphear', c.id, 'PM', '(440) 442-4300', 'Project Manager', false, 'https://www.linkedin.com/in/ashley-lanphear-41854861/' FROM companies c WHERE c.name='Panzica Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ashley Lanphear' AND company_id=c.id);

-- Ruscilli Construction (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Robert Minshall', c.id, 'ESTIMATOR', '(614) 876-9484', 'VP of Preconstruction & Estimating', true, 'https://www.linkedin.com/in/robertminshall/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Minshall' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Mancini', c.id, 'ESTIMATOR', '(614) 876-9484', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/michaelmancini5252/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Mancini' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jon Belviso', c.id, 'ESTIMATOR', '(614) 876-9484', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/jon-belviso-3a8aaa7/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon Belviso' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Nathaniel Clark', c.id, 'ESTIMATOR', '(614) 876-9484', 'Lead Estimator', false, 'https://www.linkedin.com/in/nathaniel-clark39/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathaniel Clark' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Rakesh Kalyan', c.id, 'ESTIMATOR', '(614) 876-9484', 'Senior Estimator', false, 'https://www.linkedin.com/in/rakesh-kalyan-03a08036/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rakesh Kalyan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Britney Clemans', c.id, 'ESTIMATOR', '(614) 876-9484', 'Senior Estimator', false, 'https://www.linkedin.com/in/britney-williams-33952bb3/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Britney Clemans' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'David Cunningham', c.id, 'ESTIMATOR', '(614) 876-9484', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/david-cunningham-b6737193/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Cunningham' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Shannon Brown', c.id, 'PM', '(614) 876-9484', 'Project Executive', true, 'https://www.linkedin.com/in/shannon-brown-ccm-leed%c2%ae-ga-6822041a/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shannon Brown' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Todd Moroz', c.id, 'PM', '(614) 876-9484', 'Senior Project Manager', false, 'https://www.linkedin.com/in/todd-moroz-5525b08/' FROM companies c WHERE c.name='Ruscilli Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Todd Moroz' AND company_id=c.id);

-- Elford, Inc. (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Carlo Burns', c.id, 'ESTIMATOR', '(614) 488-4000', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/carlo-burns-122a257/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Carlo Burns' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Chad Morgan', c.id, 'ESTIMATOR', '(614) 488-4000', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/chad-morgan-49300958/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chad Morgan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Christopher Italiano', c.id, 'PM', '(614) 488-4000', 'Senior Project Manager / Project Executive', true, 'https://www.linkedin.com/in/AEMAAAJXleIBDmGx3cCyku14kgLpITjD0ZQGROQ/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher Italiano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Matt Kemme', c.id, 'PM', '(614) 488-4000', 'Project Executive', true, 'https://www.linkedin.com/in/matt-kemme-99814889/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Kemme' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Chris Conrad', c.id, 'PM', '(614) 488-4000', 'Project Executive', true, 'https://www.linkedin.com/in/chris-conrad-b543511b/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Conrad' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Rohan Bhat', c.id, 'PM', '(614) 488-4000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/rohan-bhat-a9a01b25/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rohan Bhat' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Justin Flores', c.id, 'PM', '(614) 488-4000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/justin-flores-18638163/' FROM companies c WHERE c.name='Elford, Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Flores' AND company_id=c.id);

-- Setterlin Building Company (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Marc Graf', c.id, 'ESTIMATOR', '(614) 459-7077', 'Chief Estimator', true, 'https://www.linkedin.com/in/marc-graf-078aa8101/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Marc Graf' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Jordan Spano', c.id, 'ESTIMATOR', '(614) 459-7077', 'Estimator', false, 'https://www.linkedin.com/in/jordanspano/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jordan Spano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Andrew Currie', c.id, 'ESTIMATOR', '(614) 459-7077', 'Estimator', false, 'https://www.linkedin.com/in/andrew-currie-77a6b115/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Currie' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Justin Metzler', c.id, 'ESTIMATOR', '(614) 459-7077', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/jmetzler/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Metzler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Adam Wilcox', c.id, 'ESTIMATOR', '(614) 459-7077', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/adam-wilcox-236513131/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Wilcox' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Scott Forshey', c.id, 'PM', '(614) 459-7077', 'Project Executive', true, 'https://www.linkedin.com/in/scott-forshey-ab28863/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Forshey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Adam Crabtree', c.id, 'PM', '(614) 459-7077', 'Project Manager', false, 'https://www.linkedin.com/in/adam-crabtree-b9370165/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Crabtree' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Striker Loudermilk', c.id, 'PM', '(614) 459-7077', 'Project Manager', false, 'https://www.linkedin.com/in/striker-loudermilk-50a92a1a/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Striker Loudermilk' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Shean', c.id, 'PM', '(614) 459-7077', 'Project Manager', false, 'https://www.linkedin.com/in/michael-shean-98b76a24/' FROM companies c WHERE c.name='Setterlin Building Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Shean' AND company_id=c.id);

-- Skoda Construction Inc. (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'Michael Skoda', c.id, 'PM', '(216) 214-3142', 'Vice President', true, 'https://www.linkedin.com/in/michael-skoda-02573837/' FROM companies c WHERE c.name='Skoda Construction Inc.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Skoda' AND company_id=c.id);
