-- 00040_seed_oh_gc_contacts_batch2.sql
-- Seed OH GCs batch 2: 4 companies + 34 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint).

-- ============================================================
-- COMPANIES (with website)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Higley Construction', 'GC', 'OH', 'Cleveland, OH', '(216) 861-2050', 'https://www.higleybuilds.com', 'Cleveland', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Higley Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Shook Construction', 'GC', 'OH', 'Moraine, OH', '(937) 276-6666', 'https://www.shookconstruction.com', 'Moraine', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Shook Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Donley''s', 'GC', 'OH', 'Cleveland, OH', '(216) 524-6800', 'https://www.donleyinc.com', 'Cleveland', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Donley''s');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Danis', 'GC', 'OH', 'Miamisburg, OH', '(937) 228-1225', 'https://www.danis.com', 'Miamisburg', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Danis');

-- ============================================================
-- CONTACTS (34)
-- ============================================================

-- Higley Construction (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Gino Bravo', c.id, 'ESTIMATOR', '(216) 861-2050', 'Chief Estimator', true, 'https://www.linkedin.com/in/gino-bravo-7b67ab124/', 'Morristown', 'NJ' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Gino Bravo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url) SELECT 'TJ Pasadyn', c.id, 'ESTIMATOR', '(216) 861-2050', 'Corporate Director of Preconstruction', true, 'https://www.linkedin.com/in/tj-pasadyn-924093110/' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='TJ Pasadyn' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Adam Lantvit', c.id, 'ESTIMATOR', '(216) 861-2050', 'Director of Preconstruction, Ohio', true, 'https://www.linkedin.com/in/adam-lantvit-se-pe-1118187/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Lantvit' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matt Tushis', c.id, 'ESTIMATOR', '(216) 861-2050', 'Sr. Preconstruction Manager', false, 'https://www.linkedin.com/in/matt-tushis-482010a/', 'Detroit', 'MI' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Tushis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David J. Meehan', c.id, 'PM', '(216) 861-2050', 'Project Executive', true, 'https://www.linkedin.com/in/david-j-meehan-6b79516/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David J. Meehan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Robert Garuccio', c.id, 'PM', '(216) 861-2050', 'Project Executive', true, 'https://www.linkedin.com/in/robert-garuccio-5b79a946/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Garuccio' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Randy Hamilton', c.id, 'PM', '(216) 861-2050', 'Project Executive', true, 'https://www.linkedin.com/in/randy-hamilton-2593b835/', 'Berea', 'OH' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Randy Hamilton' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Aaron Paczkowski', c.id, 'PM', '(216) 861-2050', 'Project Executive', true, 'https://www.linkedin.com/in/aaron-paczkowski-79b65180/', 'Grosse Pointe', 'MI' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Aaron Paczkowski' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Andrew Holewinski', c.id, 'PM', '(216) 861-2050', 'Project Executive', true, 'https://www.linkedin.com/in/andrew-holewinski-9a609014/', 'Brighton', 'MI' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Holewinski' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Logan Pringle', c.id, 'PM', '(216) 861-2050', 'Project Manager', false, 'https://www.linkedin.com/in/logan-pringle-59160947/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Higley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Logan Pringle' AND company_id=c.id);

-- Shook Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matt Huelsman', c.id, 'ESTIMATOR', '(937) 276-6666', 'Director of Preconstruction, Midwest', true, 'https://www.linkedin.com/in/matt-huelsman-4843b92b/', 'Dayton', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Huelsman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Nystrom', c.id, 'ESTIMATOR', '(937) 276-6666', 'Lead Estimator', false, 'https://www.linkedin.com/in/david-nystrom-34372443/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Nystrom' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Richard Zahoranski', c.id, 'ESTIMATOR', '(937) 276-6666', 'Lead Estimator', false, 'https://www.linkedin.com/in/richard-zahoranski-0744b44/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Zahoranski' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Riley Tolen', c.id, 'ESTIMATOR', '(937) 276-6666', 'Lead Estimator', false, 'https://www.linkedin.com/in/riley-tolen-1843235b/', 'Apex', 'NC' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Riley Tolen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dylan Blair', c.id, 'ESTIMATOR', '(937) 276-6666', 'Estimator', false, 'https://www.linkedin.com/in/dylan-blair-495872173/', 'Dayton', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dylan Blair' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tim Knueve', c.id, 'PM', '(937) 276-6666', 'Project Executive, Midwest', true, 'https://www.linkedin.com/in/timknueve/', 'Dayton', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tim Knueve' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Marcus Pickworth', c.id, 'PM', '(937) 276-6666', 'Senior Project Manager', false, 'https://www.linkedin.com/in/marcus-pickworth-hcc-43907973/', 'Dayton', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Marcus Pickworth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jaron Develbiss', c.id, 'PM', '(937) 276-6666', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jaron-develbiss-1b037127/', 'Dayton', 'OH' FROM companies c WHERE c.name='Shook Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jaron Develbiss' AND company_id=c.id);

-- Donley's (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tom Heginbotham', c.id, 'ESTIMATOR', '(216) 524-6800', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/tom-heginbotham-41b9b4a/', 'Hudson', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tom Heginbotham' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Timothy Mescher', c.id, 'ESTIMATOR', '(216) 524-6800', 'Senior Estimator', false, 'https://www.linkedin.com/in/timothy-mescher-dbia-1900341a/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Timothy Mescher' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Barry Breedlove', c.id, 'ESTIMATOR', '(216) 524-6800', 'Senior Estimator', false, 'https://www.linkedin.com/in/barry-breedlove-774b95149/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Barry Breedlove' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Joshua Anthony', c.id, 'ESTIMATOR', '(216) 524-6800', 'Construction Estimator', false, 'https://www.linkedin.com/in/joshua-anthony-015860237/', 'Chagrin Falls', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joshua Anthony' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eric Nutter', c.id, 'PM', '(216) 524-6800', 'Project Manager', false, 'https://www.linkedin.com/in/eric-nutter-5464751a/', 'Mentor', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Nutter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Michael Schiavoni', c.id, 'PM', '(216) 524-6800', 'Project Manager', false, 'https://www.linkedin.com/in/michael-schiavoni-10b8255a/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Schiavoni' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Clay Haselden', c.id, 'PM', '(216) 524-6800', 'Project Executive', true, 'https://www.linkedin.com/in/clay-haselden-47311787/', 'Lanexa', 'VA' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Clay Haselden' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tim Christopher', c.id, 'ESTIMATOR', '(216) 524-6800', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/tim-christopher-6a203882/', 'Oak Ridge', 'NC' FROM companies c WHERE c.name='Donley''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tim Christopher' AND company_id=c.id);

-- Danis (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kevin H. Apling', c.id, 'ESTIMATOR', '(937) 228-1225', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/kevin-h-apling-3a69a39/', 'Miamisburg', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kevin H. Apling' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Schmitt', c.id, 'ESTIMATOR', '(937) 228-1225', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/jason-schmitt-chc-985a436/', 'Raleigh', 'NC' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Schmitt' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris McCarthy', c.id, 'ESTIMATOR', '(937) 228-1225', 'Chief Estimator', true, 'https://www.linkedin.com/in/chris-mccarthy-cpe-64254111/', 'Dayton', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris McCarthy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dylan Simpkins', c.id, 'ESTIMATOR', '(937) 228-1225', 'Construction Estimator', false, 'https://www.linkedin.com/in/dylan-simpkins-67b92632/', 'Lebanon', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dylan Simpkins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Daniel Vornhagen', c.id, 'ESTIMATOR', '(937) 228-1225', 'Pre-Construction Manager', false, 'https://www.linkedin.com/in/daniel-vornhagen-31338a33/', 'Miamisburg', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Vornhagen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Richie Markwell', c.id, 'PM', '(937) 228-1225', 'Project Manager', false, 'https://www.linkedin.com/in/richie-markwell-a2547910a/', 'Columbus', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richie Markwell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Patrick Mason', c.id, 'PM', '(937) 228-1225', 'Project Manager', false, 'https://www.linkedin.com/in/patrick-mason-2662a734/', 'Cincinnati', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Patrick Mason' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Green', c.id, 'PM', '(937) 228-1225', 'Senior Project Manager', false, 'https://www.linkedin.com/in/mike-green-5aa2bb34/', 'Columbus', 'OH' FROM companies c WHERE c.name='Danis' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Green' AND company_id=c.id);
