-- 00043_seed_dcmd_gc_contacts.sql
-- Seed DC/MD GCs: 10 companies + 138 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line. linkedin_url + city/state = NULL for contacts.
-- "Clark Construction Group" (Bethesda MD) is DISTINCT from "Clark Construction Company" (Lansing MI).

-- ============================================================
-- COMPANIES
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'DAVIS Construction', 'GC', 'MD', 'Rockville, MD', '(301) 881-2990', 'https://www.davisconstruction.com', 'Rockville', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'DAVIS Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Coakley & Williams Construction', 'GC', 'MD', 'Gaithersburg, MD', '(301) 963-5000', 'https://www.coakleywilliams.com', 'Gaithersburg', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Coakley & Williams Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Grunley Construction', 'GC', 'MD', 'Rockville, MD', '(240) 399-2000', 'https://www.grunley.com', 'Rockville', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Grunley Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Forrester Construction', 'GC', 'MD', 'Rockville, MD', '(301) 816-1700', 'https://www.forresterconstruction.com', 'Rockville', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Forrester Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Clark Construction Group', 'GC', 'MD', 'Bethesda, MD', '(301) 272-8100', 'https://www.clarkconstruction.com', 'Bethesda', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Clark Construction Group');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Harkins Builders', 'GC', 'MD', 'Columbia, MD', '(410) 750-2600', 'https://www.harkinsbuilders.com', 'Columbia', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Harkins Builders');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Bozzuto Construction', 'GC', 'MD', 'Greenbelt, MD', '(301) 220-0100', 'https://www.bozzuto.com', 'Greenbelt', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Bozzuto Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'MCN Build', 'GC', 'DC', 'Washington, DC', '(202) 333-3424', 'https://www.mcnbuild.com', 'Washington', 'DC' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'MCN Build');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Henley Construction', 'GC', 'MD', 'Gaithersburg, MD', '(301) 417-1006', 'https://www.henleyconstruction.com', 'Gaithersburg', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Henley Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Dustin Construction', 'GC', 'MD', 'Gaithersburg, MD', '(301) 810-4320', 'https://www.dustinconstruction.com', 'Gaithersburg', 'MD' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Dustin Construction');

-- ============================================================
-- CONTACTS (138)
-- ============================================================

-- DAVIS Construction (15)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Bennie Kovach', c.id, 'ESTIMATOR', '(301) 881-2990', 'VP - Preconstruction', true FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bennie Kovach' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Shannon Buck', c.id, 'ESTIMATOR', '(301) 881-2990', 'Senior Estimating + Preconstruction Engineer', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shannon Buck' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Tommy Vince', c.id, 'ESTIMATOR', '(301) 881-2990', 'Senior Estimating + Preconstruction Engineer', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tommy Vince' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Andrew Pino', c.id, 'ESTIMATOR', '(301) 881-2990', 'Preconstruction Executive', true FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Pino' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Alejandro Portillo', c.id, 'PM', '(301) 881-2990', 'Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alejandro Portillo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kyle Erickson', c.id, 'PM', '(301) 881-2990', 'Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kyle Erickson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Josh Kappel', c.id, 'PM', '(301) 881-2990', 'Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Kappel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ainsworth Neal', c.id, 'PM', '(301) 881-2990', 'Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ainsworth Neal' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Katharine Arsenault', c.id, 'PM', '(301) 881-2990', 'Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Katharine Arsenault' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Joe Galeano', c.id, 'PM', '(301) 881-2990', 'Senior Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joe Galeano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Adam Abramson', c.id, 'PM', '(301) 881-2990', 'Senior Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Abramson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Peter Davis', c.id, 'PM', '(301) 881-2990', 'Assistant Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Peter Davis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Christina Pace', c.id, 'PM', '(301) 881-2990', 'Assistant Project Manager', false FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christina Pace' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Adina Salomon', c.id, 'PM', '(301) 881-2990', 'Project Executive', true FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adina Salomon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jon Ellen', c.id, 'PM', '(301) 881-2990', 'Senior Vice President', true FROM companies c WHERE c.name='DAVIS Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon Ellen' AND company_id=c.id);

-- Coakley & Williams Construction (17)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Byron Mayorga', c.id, 'ESTIMATOR', '(301) 963-5000', 'Preconstruction Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Byron Mayorga' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ron Womach', c.id, 'PM', '(301) 963-5000', 'Project Executive', true FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ron Womach' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jason Shaw', c.id, 'PM', '(301) 963-5000', 'Business Unit Leader', true FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Shaw' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Megan Ross', c.id, 'PM', '(301) 963-5000', 'Senior Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Megan Ross' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Max Zarate', c.id, 'PM', '(301) 963-5000', 'Senior Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Max Zarate' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kara DiGiovanni', c.id, 'PM', '(301) 963-5000', 'Senior Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kara DiGiovanni' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Emily Fredette Harquail', c.id, 'PM', '(301) 963-5000', 'Senior Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Emily Fredette Harquail' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Candace Wiggins', c.id, 'PM', '(301) 963-5000', 'Senior Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Candace Wiggins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Adriana Amaya Perdomo', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adriana Amaya Perdomo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kasra Haghighi', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kasra Haghighi' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ryan Pike', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Pike' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'William Hill-Pensamiento', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='William Hill-Pensamiento' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Lauren Desiderio', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lauren Desiderio' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ryan Treat', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Treat' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Preston Akers', c.id, 'PM', '(301) 963-5000', 'Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Preston Akers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Rebecca Koontz', c.id, 'PM', '(301) 963-5000', 'Assistant Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rebecca Koontz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kevin Escobar', c.id, 'PM', '(301) 963-5000', 'Assistant Project Manager', false FROM companies c WHERE c.name='Coakley & Williams Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kevin Escobar' AND company_id=c.id);

-- Grunley Construction (19)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Mark Laudo', c.id, 'ESTIMATOR', '(240) 399-2000', 'Vice President of Preconstruction', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Laudo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'David Green', c.id, 'PURCHASING', '(240) 399-2000', 'Vice President of Purchasing', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Green' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Stephen Smith', c.id, 'ESTIMATOR', '(240) 399-2000', 'Senior MEP Estimator', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Stephen Smith' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Adam Skidmore', c.id, 'PM', '(240) 399-2000', 'Project Executive', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Skidmore' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Mike Stigliano', c.id, 'PM', '(240) 399-2000', 'Project Executive', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Stigliano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kyle Erickson', c.id, 'PM', '(240) 399-2000', 'Project Executive', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kyle Erickson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Andrew Sleeth', c.id, 'PM', '(240) 399-2000', 'Project Executive', true FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Sleeth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Joseph Pirrone', c.id, 'PM', '(240) 399-2000', 'Senior Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joseph Pirrone' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kaitlyn Poland', c.id, 'PM', '(240) 399-2000', 'Senior Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kaitlyn Poland' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Adam Carroll', c.id, 'PM', '(240) 399-2000', 'Senior Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Carroll' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nicholas Albright', c.id, 'PM', '(240) 399-2000', 'Senior Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nicholas Albright' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jamie Gensits', c.id, 'PM', '(240) 399-2000', 'Senior Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jamie Gensits' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Richard Randolph', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Randolph' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Joshua Sims', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joshua Sims' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'RJ Fazio', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='RJ Fazio' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'William Prete', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='William Prete' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Alex McWhirter', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alex McWhirter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Pat Emery', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pat Emery' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Shira Hackman', c.id, 'PM', '(240) 399-2000', 'Project Manager', false FROM companies c WHERE c.name='Grunley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shira Hackman' AND company_id=c.id);

-- Forrester Construction (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ed Smith', c.id, 'PM', '(301) 816-1700', 'Senior Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ed Smith' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Asiad Kunaish', c.id, 'PM', '(301) 816-1700', 'Senior Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Asiad Kunaish' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Lamarr Mayo', c.id, 'PM', '(301) 816-1700', 'Senior Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lamarr Mayo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Mara Fitzgerald', c.id, 'PM', '(301) 816-1700', 'Senior Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mara Fitzgerald' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Rusty Russell', c.id, 'PM', '(301) 816-1700', 'Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rusty Russell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jon McGee', c.id, 'PM', '(301) 816-1700', 'Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon McGee' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'John Diggs', c.id, 'PM', '(301) 816-1700', 'Assistant Project Manager', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Diggs' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nathalee Martinez', c.id, 'PM', '(301) 816-1700', 'Senior Project Coordinator', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathalee Martinez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Takita Jenkins', c.id, 'PM', '(301) 816-1700', 'Senior Project Coordinator', false FROM companies c WHERE c.name='Forrester Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Takita Jenkins' AND company_id=c.id);

-- Clark Construction Group (13)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Bob McNey', c.id, 'ESTIMATOR', '(301) 272-8100', 'Chief Estimator', true FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bob McNey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Christopher James', c.id, 'ESTIMATOR', '(301) 272-8100', 'Senior Preconstruction Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher James' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Sid Rouholamin', c.id, 'ESTIMATOR', '(301) 272-8100', 'Senior Estimator', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sid Rouholamin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Andrew Johnson', c.id, 'ESTIMATOR', '(301) 272-8100', 'Estimator', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Johnson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Anas Alakhras', c.id, 'PM', '(301) 272-8100', 'Project Executive', true FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Anas Alakhras' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Meghan Murphy', c.id, 'PM', '(301) 272-8100', 'Project Executive', true FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Meghan Murphy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Phillip Thomas', c.id, 'PM', '(301) 272-8100', 'Senior Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Phillip Thomas' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ryan Goldstein', c.id, 'PM', '(301) 272-8100', 'Senior Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Goldstein' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ben Sistachs', c.id, 'PM', '(301) 272-8100', 'Strategic Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ben Sistachs' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Clark Pastrick', c.id, 'PM', '(301) 272-8100', 'Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Clark Pastrick' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Michael Stanton', c.id, 'PM', '(301) 272-8100', 'Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Stanton' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nhomer Estabillo', c.id, 'PM', '(301) 272-8100', 'Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nhomer Estabillo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Mark Orebiyi', c.id, 'PM', '(301) 272-8100', 'Project Manager', false FROM companies c WHERE c.name='Clark Construction Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Orebiyi' AND company_id=c.id);

-- Harkins Builders (19)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Omar Black', c.id, 'ESTIMATOR', '(410) 750-2600', 'Senior Vice President of Preconstruction', true FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Omar Black' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Todd Souder', c.id, 'ESTIMATOR', '(410) 750-2600', 'Senior Preconstruction Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Todd Souder' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'John Kim', c.id, 'ESTIMATOR', '(410) 750-2600', 'Preconstruction Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Kim' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Daniel Hefter', c.id, 'ESTIMATOR', '(410) 750-2600', 'Senior Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Hefter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Joe Humm', c.id, 'ESTIMATOR', '(410) 750-2600', 'Senior Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joe Humm' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'David Griffin', c.id, 'ESTIMATOR', '(410) 750-2600', 'Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Griffin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jordan Horne', c.id, 'ESTIMATOR', '(410) 750-2600', 'Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jordan Horne' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Scott Wilhelm', c.id, 'ESTIMATOR', '(410) 750-2600', 'Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Wilhelm' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Tyler Nalls', c.id, 'ESTIMATOR', '(410) 750-2600', 'Estimator', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Nalls' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Robert Tirocchi', c.id, 'PM', '(410) 750-2600', 'Project Executive', true FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Tirocchi' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Christopher Canapp', c.id, 'PM', '(410) 750-2600', 'Senior Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher Canapp' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Dereck Hall', c.id, 'PM', '(410) 750-2600', 'Senior Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dereck Hall' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ashford Watkins', c.id, 'PM', '(410) 750-2600', 'Senior Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ashford Watkins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nick Berry', c.id, 'PM', '(410) 750-2600', 'Senior Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Berry' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Andrew McGinn', c.id, 'PM', '(410) 750-2600', 'Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew McGinn' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Karlen Jimenez', c.id, 'PM', '(410) 750-2600', 'Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Karlen Jimenez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Bobby Widmer', c.id, 'PM', '(410) 750-2600', 'Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bobby Widmer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Austin Achenbach', c.id, 'PM', '(410) 750-2600', 'Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Austin Achenbach' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Laura Byrne', c.id, 'PM', '(410) 750-2600', 'Project Manager', false FROM companies c WHERE c.name='Harkins Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Laura Byrne' AND company_id=c.id);

-- Bozzuto Construction (16)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Simone Ray', c.id, 'PURCHASING', '(301) 220-0100', 'Senior Director of Procurement', true FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Simone Ray' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Brady Davidow', c.id, 'ESTIMATOR', '(301) 220-0100', 'Director of Preconstruction', true FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brady Davidow' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kerry Dolan', c.id, 'ESTIMATOR', '(301) 220-0100', 'Senior Preconstruction Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kerry Dolan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Melissa Camargo', c.id, 'ESTIMATOR', '(301) 220-0100', 'Senior Estimator', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Melissa Camargo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Najam Arfeen', c.id, 'ESTIMATOR', '(301) 220-0100', 'Estimator', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Najam Arfeen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Riley Edwards', c.id, 'ESTIMATOR', '(301) 220-0100', 'Estimator', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Riley Edwards' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jon Pinard', c.id, 'PM', '(301) 220-0100', 'Project Executive', true FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon Pinard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Craig Owsiany', c.id, 'PM', '(301) 220-0100', 'Senior Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Craig Owsiany' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Lisa Ford', c.id, 'PM', '(301) 220-0100', 'Senior Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lisa Ford' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Mandy Paquin', c.id, 'PM', '(301) 220-0100', 'Senior Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mandy Paquin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jim Stamas', c.id, 'PM', '(301) 220-0100', 'Senior Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Stamas' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Andrew Sheehan', c.id, 'PM', '(301) 220-0100', 'Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Sheehan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Madeleine Wolff', c.id, 'PM', '(301) 220-0100', 'Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Madeleine Wolff' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Valentina Gonzalez', c.id, 'PM', '(301) 220-0100', 'Assistant Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Valentina Gonzalez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Najla Robinson', c.id, 'PM', '(301) 220-0100', 'Assistant Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Najla Robinson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Federico Meersohn', c.id, 'PM', '(301) 220-0100', 'Assistant Project Manager', false FROM companies c WHERE c.name='Bozzuto Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Federico Meersohn' AND company_id=c.id);

-- MCN Build (19)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Korey Price', c.id, 'ESTIMATOR', '(202) 333-3424', 'Chief Estimator', true FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Korey Price' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Matthew Byrne', c.id, 'ESTIMATOR', '(202) 333-3424', 'Vice President of Preconstruction', true FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Byrne' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Joseph Khoury', c.id, 'ESTIMATOR', '(202) 333-3424', 'Director of Preconstruction', true FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joseph Khoury' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Selena Belluscio', c.id, 'ESTIMATOR', '(202) 333-3424', 'Senior Preconstruction Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Selena Belluscio' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Dean Whitehead', c.id, 'ESTIMATOR', '(202) 333-3424', 'Preconstruction Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dean Whitehead' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Rick Munford', c.id, 'ESTIMATOR', '(202) 333-3424', 'Preconstruction', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rick Munford' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Safiullah Khan', c.id, 'ESTIMATOR', '(202) 333-3424', 'Pre-Construction Estimator', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Safiullah Khan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Vaibhav Jain', c.id, 'ESTIMATOR', '(202) 333-3424', 'Project Estimator', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Vaibhav Jain' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jacob Goldsmith', c.id, 'PM', '(202) 333-3424', 'Project Director', true FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Goldsmith' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Omid Mina', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Omid Mina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Kranthi Sreenadhu', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kranthi Sreenadhu' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'John Farah', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Farah' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Sai Prakash Rajendran', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sai Prakash Rajendran' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Reza Mir', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Reza Mir' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Elias Eid', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Elias Eid' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jose Pleitez', c.id, 'PM', '(202) 333-3424', 'Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jose Pleitez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Salil Desai', c.id, 'PM', '(202) 333-3424', 'Assistant Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Salil Desai' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Ravi Mannuru', c.id, 'PM', '(202) 333-3424', 'Assistant Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ravi Mannuru' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Satish Kumar Gantasala', c.id, 'PM', '(202) 333-3424', 'Assistant Project Manager', false FROM companies c WHERE c.name='MCN Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Satish Kumar Gantasala' AND company_id=c.id);

-- Henley Construction (2)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nathan Stewart', c.id, 'PM', '(301) 417-1006', 'Project Manager', false FROM companies c WHERE c.name='Henley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathan Stewart' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Nathalia Marcano', c.id, 'PM', '(301) 417-1006', 'Assistant Project Manager', false FROM companies c WHERE c.name='Henley Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathalia Marcano' AND company_id=c.id);

-- Dustin Construction (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'John Pickett', c.id, 'ESTIMATOR', '(301) 810-4320', 'Vice President and Director of Preconstruction', true FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Pickett' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Lloyd Hill', c.id, 'ESTIMATOR', '(301) 810-4320', 'Senior Estimator', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lloyd Hill' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Melissa Hill', c.id, 'ESTIMATOR', '(301) 810-4320', 'Estimator', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Melissa Hill' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Carly Bruchey', c.id, 'ESTIMATOR', '(301) 810-4320', 'Preconstruction Coordinator', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Carly Bruchey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Josh Mitchell', c.id, 'PM', '(301) 810-4320', 'Senior Project Manager', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Mitchell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Josh Stewart', c.id, 'PM', '(301) 810-4320', 'Project Manager', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Stewart' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Jacob Clements', c.id, 'PM', '(301) 810-4320', 'Assistant Project Manager', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Clements' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Emily Reeder', c.id, 'PM', '(301) 810-4320', 'Assistant Project Manager', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Emily Reeder' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker) SELECT 'Shelby Lorincz', c.id, 'PM', '(301) 810-4320', 'Assistant Project Manager', false FROM companies c WHERE c.name='Dustin Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shelby Lorincz' AND company_id=c.id);
