-- 00045_seed_national_gc_batch1.sql
-- Seed national GCs batch 1: 11 companies + 97 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint).
-- "ARCO Design/Build" is DISTINCT from any existing "ARCO/Murray".

-- ============================================================
-- COMPANIES (11)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Barton Malow', 'GC', 'MI', 'Southfield, MI', '(248) 436-5000', 'https://www.bartonmalow.com', 'Southfield', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Barton Malow');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Walbridge', 'GC', 'MI', 'Detroit, MI', '(313) 963-8000', 'https://www.walbridge.com', 'Detroit', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Walbridge');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Aristeo', 'GC', 'MI', 'Livonia, MI', '(734) 427-9111', 'https://www.aristeo.com', 'Livonia', 'MI' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Aristeo');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Clayco', 'GC', 'IL', 'Chicago, IL', '(312) 658-0747', 'https://www.claycorp.com', 'Chicago', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Clayco');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'ARCO Design/Build', 'GC', 'GA', 'Atlanta, GA', '(770) 541-1700', 'https://www.arcodb.com', 'Atlanta', 'GA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'ARCO Design/Build');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'FCL Builders', 'GC', 'IL', 'Itasca, IL', '(630) 773-0050', 'https://www.fclbuilders.com', 'Itasca', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'FCL Builders');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Krusinski Construction', 'GC', 'IL', 'Oak Brook, IL', '(630) 573-7700', 'https://www.krusinski.com', 'Oak Brook', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Krusinski Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Greystone Construction', 'GC', 'MN', 'Shakopee, MN', '(952) 496-2227', 'https://www.greystoneconstruction.com', 'Shakopee', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Greystone Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Opus', 'GC', 'MN', 'Minneapolis, MN', '(952) 656-4444', 'https://www.opus-group.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Opus');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Gray', 'GC', 'KY', 'Lexington, KY', '(859) 281-5000', 'https://www.gray.com', 'Lexington', 'KY' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Gray');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Dennis Group', 'GC', 'MA', 'Springfield, MA', '(413) 787-1785', 'https://www.dennisgroup.com', 'Springfield', 'MA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Dennis Group');

-- ============================================================
-- CONTACTS (97)
-- ============================================================

-- Barton Malow (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Pociask', c.id, 'ESTIMATOR', '(248) 436-5000', 'Director of Preconstruction, Barton Malow Builders', true, 'https://www.linkedin.com/in/jason-pociask-7a1a007b/', 'Detroit', 'MI' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Pociask' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Thomas Rossi', c.id, 'ESTIMATOR', '(248) 436-5000', 'Sr. Estimating Manager, Preconstruction (MEP)', false, 'https://www.linkedin.com/in/thomas-rossi-77722515/', 'Southfield', 'MI' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Thomas Rossi' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'James Kramek', c.id, 'PM', '(248) 436-5000', 'Project Executive', true, 'https://www.linkedin.com/in/james-kramek-62965510/', 'Detroit', 'MI' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='James Kramek' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Adrienne Sraver', c.id, 'PM', '(248) 436-5000', 'Project Executive', true, 'https://www.linkedin.com/in/adrienne-sraver-4b181b20/', 'Columbus', 'OH' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adrienne Sraver' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tyler Donnell', c.id, 'PM', '(248) 436-5000', 'Project Executive', true, 'https://www.linkedin.com/in/tyler-donnell-74220734/', 'Orlando', 'FL' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Donnell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Christopher Moore', c.id, 'PM', '(248) 436-5000', 'Director of Project Solutions', true, 'https://www.linkedin.com/in/christopher-moore-69570752/', 'Orlando', 'FL' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher Moore' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tulika Tahiliani', c.id, 'PURCHASING', '(248) 436-5000', 'Procurement Coordinator', false, 'https://www.linkedin.com/in/tulika-tahiliani/', NULL, NULL FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tulika Tahiliani' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nick Edsen', c.id, 'PM', '(248) 436-5000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/nick-edsen-9948475b/', 'Detroit', 'MI' FROM companies c WHERE c.name='Barton Malow' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Edsen' AND company_id=c.id);

-- Walbridge (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jim Quasarano', c.id, 'ESTIMATOR', '(313) 963-8000', 'Vice President, Preconstruction', true, 'https://www.linkedin.com/in/jim-quasarano-15a0252/', 'Detroit', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Quasarano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Daniel Wulf', c.id, 'ESTIMATOR', '(313) 963-8000', 'Director, Preconstruction', true, 'https://www.linkedin.com/in/daniel-wulf-49212b64/', 'Detroit', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Wulf' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Williams', c.id, 'ESTIMATOR', '(313) 963-8000', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/mike-williams-6b0a114/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Williams' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jacob Millyard', c.id, 'ESTIMATOR', '(313) 963-8000', 'Sr. Preconstruction Manager', false, 'https://www.linkedin.com/in/jacob-r-millyard-p-e-578a9a64/', 'Detroit', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Millyard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Cusano', c.id, 'ESTIMATOR', '(313) 963-8000', 'Senior Preconstruction Manager', false, 'https://www.linkedin.com/in/mike-cusano-932a7ba3/', 'Kalamazoo', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Cusano' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tim Dickinson', c.id, 'ESTIMATOR', '(313) 963-8000', 'Chief Estimator', true, 'https://www.linkedin.com/in/tim-dickinson-967674b/', 'Farmington', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tim Dickinson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ankur Agrawal', c.id, 'ESTIMATOR', '(313) 963-8000', 'Senior Estimator', false, 'https://www.linkedin.com/in/agrawalankur28/', 'Lake Orion', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ankur Agrawal' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Daniel Lindenmuth', c.id, 'ESTIMATOR', '(313) 963-8000', 'Estimator', false, 'https://www.linkedin.com/in/daniel-lindenmuth-pe-979337149/', 'Ann Arbor', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Lindenmuth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Steven Sahadi', c.id, 'PURCHASING', '(313) 963-8000', 'Procurement Specialist', false, 'https://www.linkedin.com/in/steven-sahadi-305761142/', 'Grosse Pointe', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Sahadi' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Madison Charles', c.id, 'PURCHASING', '(313) 963-8000', 'Procurement Coordinator', false, 'https://www.linkedin.com/in/madison-charles-54a5151b7/', 'Detroit', 'MI' FROM companies c WHERE c.name='Walbridge' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Madison Charles' AND company_id=c.id);

-- Aristeo (11)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Salazar', c.id, 'ESTIMATOR', '(734) 427-9111', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/jason-salazar-michigan/', 'Detroit', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Salazar' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Graham Tidbury', c.id, 'ESTIMATOR', '(734) 427-9111', 'Chief Estimator', true, 'https://www.linkedin.com/in/graham-tidbury-57596612/', 'Livonia', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Graham Tidbury' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kyle Reynolds', c.id, 'ESTIMATOR', '(734) 427-9111', 'Chief Estimator', true, 'https://www.linkedin.com/in/kyle-reynolds-b7674384/', 'Commerce', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kyle Reynolds' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nick Schallmo', c.id, 'ESTIMATOR', '(734) 427-9111', 'Chief Estimator', true, 'https://www.linkedin.com/in/nick-schallmo-b0653a4/', 'Detroit', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Schallmo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brandon Adler', c.id, 'ESTIMATOR', '(734) 427-9111', 'Lead Estimator', false, 'https://www.linkedin.com/in/brandon-adler-643765193/', 'Detroit', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Adler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Damon Gulette', c.id, 'ESTIMATOR', '(734) 427-9111', 'Lead Estimator', false, 'https://www.linkedin.com/in/damon-gulette-5490b217a/', 'Redford', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Damon Gulette' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'George Lucero', c.id, 'ESTIMATOR', '(734) 427-9111', 'Estimator', false, 'https://www.linkedin.com/in/lucerogf/', 'Detroit', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='George Lucero' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Patrick McCarthy', c.id, 'PM', '(734) 427-9111', 'Project Executive', true, 'https://www.linkedin.com/in/patrick-mccarthy-bb188635/', 'Walled Lake', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Patrick McCarthy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Scott Kazura', c.id, 'PM', '(734) 427-9111', 'Project Executive', true, 'https://www.linkedin.com/in/scott-kazura-bb5a686/', 'Toledo', 'OH' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Kazura' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Anthony LaRosa', c.id, 'PM', '(734) 427-9111', 'Project Director', true, 'https://www.linkedin.com/in/anthony-larosa-36a96718/', 'Northville', 'MI' FROM companies c WHERE c.name='Aristeo' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Anthony LaRosa' AND company_id=c.id);

-- Clayco (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kurt Jaeger', c.id, 'ESTIMATOR', '(312) 658-0747', 'Executive Vice President, Preconstruction', true, 'https://www.linkedin.com/in/kurt-jaeger-b898b09/', 'St. Louis', 'MO' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kurt Jaeger' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Conor Tighe', c.id, 'ESTIMATOR', '(312) 658-0747', 'EVP, Preconstruction & Procurement Strategy', true, 'https://www.linkedin.com/in/conor-tighe-06922115/', 'Highland Park', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Conor Tighe' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dave Bartolai', c.id, 'ESTIMATOR', '(312) 658-0747', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/dbartolai/', 'Chicago', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dave Bartolai' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Daniel', c.id, 'ESTIMATOR', '(312) 658-0747', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/brian-daniel-9587474/', 'Chicago', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Daniel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Taeho Lee', c.id, 'ESTIMATOR', '(312) 658-0747', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/taeho-lee-pe-leed-ap-153bb28/', 'Chicago', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Taeho Lee' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jared Broghamer', c.id, 'ESTIMATOR', '(312) 658-0747', 'Director of Preconstruction - Solar', true, 'https://www.linkedin.com/in/jared-broghamer-2680235/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jared Broghamer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jon May', c.id, 'PM', '(312) 658-0747', 'Project Executive', true, 'https://www.linkedin.com/in/jonedmayeit/', 'Chicago', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon May' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kent DeRusha', c.id, 'PM', '(312) 658-0747', 'Project Executive', true, 'https://www.linkedin.com/in/kent-derusha-pmp-dbia-cp-ace-3996508/', NULL, NULL FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kent DeRusha' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Baldock', c.id, 'PM', '(312) 658-0747', 'Sr. Project Director', true, 'https://www.linkedin.com/in/brian-baldock-b77a6210/', 'Chicago', 'IL' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Baldock' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Walker', c.id, 'PM', '(312) 658-0747', 'Sr. Project Director', true, 'https://www.linkedin.com/in/john-walker-b81a4323/', 'St. Clair Shores', 'MI' FROM companies c WHERE c.name='Clayco' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Walker' AND company_id=c.id);

-- ARCO Design/Build (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jordan Jenkins', c.id, 'PM', '(770) 541-1700', 'Senior Design/Build Manager', false, 'https://www.linkedin.com/in/jordan-jenkins-6a922b157/', 'Houston', 'TX' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jordan Jenkins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dakota Warner', c.id, 'PM', '(770) 541-1700', 'Senior MEP Project Manager', false, 'https://www.linkedin.com/in/dakota-warner-92b22833a/', NULL, NULL FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dakota Warner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Woods', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/jasonwoods347/', 'Atlanta', 'GA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Woods' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Shaffer Lisle', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/shaffer-lisle-130b13172/', 'Atlanta', 'GA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shaffer Lisle' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nathan Densmore', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/nathan-densmore-b311634b/', 'Cumming', 'GA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathan Densmore' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ian O''Mahony', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/ian-o-mahony-514414197/', 'Atlanta', 'GA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ian O''Mahony' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike McCullough', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/mmccullough13/', 'Philadelphia', 'PA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike McCullough' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Giovanni Santoro', c.id, 'PM', '(770) 541-1700', 'Project Manager', false, 'https://www.linkedin.com/in/giovanni-santoro-59937a14a/', 'King of Prussia', 'PA' FROM companies c WHERE c.name='ARCO Design/Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Giovanni Santoro' AND company_id=c.id);

-- FCL Builders (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tony Sanders', c.id, 'ESTIMATOR', '(630) 773-0050', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/tony-sanders-40b385bb/', 'Buford', 'GA' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tony Sanders' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rodney Greenfield', c.id, 'ESTIMATOR', '(630) 773-0050', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/rodney-greenfield-40087434/', 'Baltimore', 'MD' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rodney Greenfield' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tom Dennis', c.id, 'ESTIMATOR', '(630) 773-0050', 'Senior Estimator', false, 'https://www.linkedin.com/in/tom-dennis-36546531/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tom Dennis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Miguel Stark', c.id, 'ESTIMATOR', '(630) 773-0050', 'Project Estimator', false, 'https://www.linkedin.com/in/miguel-stark-6b3b639b/', 'Houston', 'TX' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Miguel Stark' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Colby Henson-Poole', c.id, 'ESTIMATOR', '(630) 773-0050', 'Project Estimator', false, 'https://www.linkedin.com/in/colby-henson-4072a817b/', 'Atlanta', 'GA' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Colby Henson-Poole' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Richard Colon Jr', c.id, 'ESTIMATOR', '(630) 773-0050', 'Sr. Project Estimator / Project Manager', false, 'https://www.linkedin.com/in/richard-col%c3%b3n-jr-5b81b2a8/', 'Millersville', 'MD' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Colon Jr' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Thueson', c.id, 'PM', '(630) 773-0050', 'Project Executive', true, 'https://www.linkedin.com/in/david-thueson-a78a471b/', 'Los Alamitos', 'CA' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Thueson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tray Hardin', c.id, 'PM', '(630) 773-0050', 'Project Executive', true, 'https://www.linkedin.com/in/trayhardin/', 'Midlothian', 'TX' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tray Hardin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Blake McClendon', c.id, 'PM', '(630) 773-0050', 'Director of Construction - Houston', true, 'https://www.linkedin.com/in/blakemcclendon/', 'Houston', 'TX' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Blake McClendon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Carie Carney', c.id, 'PM', '(630) 773-0050', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/carie-carney-0b096117/', 'Itasca', 'IL' FROM companies c WHERE c.name='FCL Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Carie Carney' AND company_id=c.id);

-- Krusinski Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Brady', c.id, 'ESTIMATOR', '(630) 573-7700', 'Pre-Construction Director', true, 'https://www.linkedin.com/in/john-brady-51718bb/', 'Oak Brook', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Brady' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Steve Dompke', c.id, 'ESTIMATOR', '(630) 573-7700', 'Senior Preconstruction Manager', false, 'https://www.linkedin.com/in/steve-dompke-75303410/', 'Palatine', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steve Dompke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Yvette Hianik', c.id, 'ESTIMATOR', '(630) 573-7700', 'Pre-Construction Manager', false, 'https://www.linkedin.com/in/yvette-hianik-81338416/', 'Oak Brook', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Yvette Hianik' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Pablo Aquino', c.id, 'ESTIMATOR', '(630) 573-7700', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/pablo-aquino-33528134/', 'Chicago', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pablo Aquino' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rich Melone', c.id, 'PM', '(630) 573-7700', 'Project Executive', true, 'https://www.linkedin.com/in/rich-melone-a628419/', 'Chicago', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rich Melone' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Craig Kenmotsu', c.id, 'PM', '(630) 573-7700', 'Project Executive', true, 'https://www.linkedin.com/in/craig-kenmotsu-596a4b5/', 'Downers Grove', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Craig Kenmotsu' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ryan Lehman', c.id, 'PM', '(630) 573-7700', 'Senior Project Manager', false, 'https://www.linkedin.com/in/ryan-lehman-a4879160/', 'Naperville', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Lehman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kuy Parker', c.id, 'PM', '(630) 573-7700', 'Project Manager', false, 'https://www.linkedin.com/in/kuy-parker-811583101/', 'Chicago', 'IL' FROM companies c WHERE c.name='Krusinski Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kuy Parker' AND company_id=c.id);

-- Greystone Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Geoffrey West', c.id, 'PM', '(952) 496-2227', 'Director of Construction', true, 'https://www.linkedin.com/in/geoffrey-w-west-pmp-162b65a/', 'Georgetown', 'TX' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Geoffrey West' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Hartman', c.id, 'ESTIMATOR', '(952) 496-2227', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/david-hartman-65003940/', 'Jordan', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Hartman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Craig Domnick', c.id, 'ESTIMATOR', '(952) 496-2227', 'Preconstruction Design Manager', false, 'https://www.linkedin.com/in/craig-domnick-0b643418/', 'Appleton', 'WI' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Craig Domnick' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Reed Baillargeon', c.id, 'ESTIMATOR', '(952) 496-2227', 'Estimator / Project Coordinator', false, 'https://www.linkedin.com/in/reed-baillargeon-24462b104/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Reed Baillargeon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Justin Hicks', c.id, 'PM', '(952) 496-2227', 'Senior Construction Manager', false, 'https://www.linkedin.com/in/justin-hicks-302b5872/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Hicks' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jim Bystrzycki', c.id, 'PM', '(952) 496-2227', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jimbystrzycki1/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Bystrzycki' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Christian Mertz', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'https://www.linkedin.com/in/christian-mertz/', 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christian Mertz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brandon Gorder', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'https://www.linkedin.com/in/brandon-gorder-m-b-a-81aa74a/', 'Cottage Grove', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Gorder' AND company_id=c.id);

-- Opus (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Luke Albers', c.id, 'PM', '(952) 656-4444', 'Project Executive', true, 'https://www.linkedin.com/in/luke-albers-646aaa11/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Luke Albers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eric Ryan', c.id, 'PM', '(952) 656-4444', 'Project Executive', true, 'https://www.linkedin.com/in/ericdryan/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Ryan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'George Parrino', c.id, 'PM', '(952) 656-4444', 'Construction Project Executive', true, 'https://www.linkedin.com/in/george-parrino-1a254176/', 'Hopkins', 'MN' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='George Parrino' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rick Tucker', c.id, 'PM', '(952) 656-4444', 'Project Executive', true, 'https://www.linkedin.com/in/rick-tucker-a4a8266/', 'Des Moines', 'IA' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rick Tucker' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Megan Hunsberger Garner', c.id, 'PM', '(952) 656-4444', 'Project Executive', true, 'https://www.linkedin.com/in/megan-hunsberger-garner-85775b102/', 'Kansas City', 'MO' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Megan Hunsberger Garner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'William Gallagher', c.id, 'PM', '(952) 656-4444', 'Senior Project Manager', false, 'https://www.linkedin.com/in/william-trey-gallagher-55b58146/', 'Chicago', 'IL' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='William Gallagher' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dave Strzelecki', c.id, 'PM', '(952) 656-4444', 'Project Manager', false, 'https://www.linkedin.com/in/david-strzelecki/', 'Chicago', 'IL' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dave Strzelecki' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jacob Mocny', c.id, 'PM', '(952) 656-4444', 'Project Manager', false, 'https://www.linkedin.com/in/jacob-mocny/', 'Chicago', 'IL' FROM companies c WHERE c.name='Opus' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Mocny' AND company_id=c.id);

-- Gray (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Paul Kornman', c.id, 'PM', '(859) 281-5000', 'Project Executive, Food & Beverage', true, 'https://www.linkedin.com/in/paul-kornman-aa4a5769/', 'Lexington', 'KY' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Paul Kornman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Timothy Sandberg', c.id, 'PM', '(859) 281-5000', 'Project Executive (Cold Storage / Food & Beverage)', true, 'https://www.linkedin.com/in/timothyjsandberg/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Timothy Sandberg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brennan Batey', c.id, 'ESTIMATOR', '(859) 281-5000', 'Assistant Director, Preconstruction', true, 'https://www.linkedin.com/in/brennan-batey-a260bb19/', 'Birmingham', 'AL' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brennan Batey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Darrell Langstaff', c.id, 'ESTIMATOR', '(859) 281-5000', 'Sr. Preconstruction Manager - Electrical Services', false, 'https://www.linkedin.com/in/darrell-langstaff-7558a2113/', NULL, NULL FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Darrell Langstaff' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Clint Richmond', c.id, 'PM', '(859) 281-5000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/clint-richmond-p-e-0a551621/', 'Dallas-Fort Worth', 'TX' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Clint Richmond' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matthew Youngblood', c.id, 'PM', '(859) 281-5000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/matthew-youngblood-98b369133/', 'Birmingham', 'AL' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Youngblood' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Gary McCray', c.id, 'PM', '(859) 281-5000', 'Project Manager', false, 'https://www.linkedin.com/in/gary-mccray-pmp-a497a4/', 'Gilbert', 'AZ' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Gary McCray' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jack Burke', c.id, 'PM', '(859) 281-5000', 'Project Manager', false, 'https://www.linkedin.com/in/jack-burke-bb0528a4/', 'Sunbury', 'OH' FROM companies c WHERE c.name='Gray' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jack Burke' AND company_id=c.id);

-- Dennis Group (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kyle Kartchner', c.id, 'PM', '(413) 787-1785', 'Partner', true, 'https://www.linkedin.com/in/kyle-kartchner-p-e-ba12888/', 'Carlsbad', 'CA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kyle Kartchner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Frank De Vries', c.id, 'PM', '(413) 787-1785', 'Sr. Program Manager', false, 'https://www.linkedin.com/in/4frankdevries/', 'Philadelphia', 'PA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Frank De Vries' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Coates', c.id, 'PM', '(413) 787-1785', 'Construction Manager', false, 'https://www.linkedin.com/in/brian-coates-b02969b/', 'Bartonsville', 'PA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Coates' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Adrian Nunez', c.id, 'PM', '(413) 787-1785', 'Construction Manager', false, 'https://www.linkedin.com/in/adrian-nunez-ctp-a3a89a177/', 'New York', 'NY' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adrian Nunez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Raymond Remillard', c.id, 'PM', '(413) 787-1785', 'Project Manager III', false, 'https://www.linkedin.com/in/raymond-remillard-34b39a106/', 'Springfield', 'MA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Raymond Remillard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Sid Nannapaneni', c.id, 'PM', '(413) 787-1785', 'Project Manager', false, 'https://www.linkedin.com/in/sid-nannapaneni/', 'Atlanta', 'GA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sid Nannapaneni' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Gilbert', c.id, 'PM', '(413) 787-1785', 'Project Manager', false, 'https://www.linkedin.com/in/jason-gilbert-b3b84b5/', 'San Diego', 'CA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Gilbert' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ejaz Chunawala', c.id, 'PM', '(413) 787-1785', 'Project Manager & Packaging Office Lead', false, 'https://www.linkedin.com/in/ejaz-chunawala-80681213/', 'Los Angeles', 'CA' FROM companies c WHERE c.name='Dennis Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ejaz Chunawala' AND company_id=c.id);
