-- 00049_seed_hr_ll_builders.sql
-- Seed Sioux-area GCs: 2 companies + 15 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint).

-- ============================================================
-- COMPANIES (2)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'H & R Construction Co.', 'GC', 'NE', 'South Sioux City, NE', '(402) 412-3550', 'https://www.hnrco.com', 'South Sioux City', 'NE' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'H & R Construction Co.');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'L & L Builders', 'GC', 'IA', 'Sioux City, IA', '(712) 255-0657', 'https://llbuilders.com', 'Sioux City', 'IA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'L & L Builders');

-- ============================================================
-- CONTACTS (15)
-- ============================================================

-- H & R Construction Co. (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nathan Herbst', c.id, 'PM', '(402) 412-3550', 'President', true, 'https://www.linkedin.com/in/nathan-herbst-7b93895/', 'South Sioux City', 'NE' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nathan Herbst' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Richard Locklear', c.id, 'PM', '(402) 412-3550', 'Vice President', true, 'https://www.linkedin.com/in/richard-locklear-9948021b8/', 'Lumberton', 'NC' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Locklear' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rick Hadlock', c.id, 'PM', '(402) 412-3550', 'Vice President', true, 'https://www.linkedin.com/in/rick-hadlock-7b7123113/', 'Algonquin', 'IL' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rick Hadlock' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Colton Webner', c.id, 'ESTIMATOR', '(402) 412-3550', 'Project Manager & Estimator', false, 'https://www.linkedin.com/in/coltonwebner/', 'Merrill', 'IA' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Colton Webner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mitch Connot', c.id, 'PM', '(402) 412-3550', 'Project Manager', false, 'https://www.linkedin.com/in/mitch-connot-6362b4119/', 'Sioux City', 'IA' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mitch Connot' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Greg Topf', c.id, 'PM', '(402) 412-3550', 'Project Manager', false, 'https://www.linkedin.com/in/greg-topf-1a306b165/', 'Sioux City', 'IA' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Greg Topf' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eric Allen', c.id, 'PM', '(402) 412-3550', 'Project Manager', false, 'https://www.linkedin.com/in/eric-allen-25257ba6/', 'South Sioux City', 'NE' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Allen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kirk Tietz', c.id, 'SUPER', '(402) 412-3550', 'Project Superintendent, LEED AP BD+C', false, 'https://www.linkedin.com/in/kirk-tietz-a3a54340/', 'Brainerd', 'MN' FROM companies c WHERE c.name='H & R Construction Co.' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kirk Tietz' AND company_id=c.id);

-- L & L Builders (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Evan Palsma', c.id, 'PM', '(712) 255-0657', 'Senior Project Manager', false, 'https://www.linkedin.com/in/evan-palsma-26181a19/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Evan Palsma' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Todd Benson', c.id, 'ESTIMATOR', '(712) 255-0657', 'Project Manager / Estimator', false, 'https://www.linkedin.com/in/todd-benson-34327720/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Todd Benson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris Stamm', c.id, 'ESTIMATOR', '(712) 255-0657', 'Estimator / Project Manager', false, 'https://www.linkedin.com/in/chris-stamm-82129636/', 'South Sioux City', 'NE' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Stamm' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'TJ Wilcke', c.id, 'ESTIMATOR', '(712) 255-0657', 'Preconstruction Manager', true, 'https://www.linkedin.com/in/tj-wilcke-12386b18b/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='TJ Wilcke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jim Mauer', c.id, 'PM', '(712) 255-0657', 'Operations Manager', true, 'https://www.linkedin.com/in/jim-mauer-1156a8b3/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Mauer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Octavio Soria', c.id, 'PM', '(712) 255-0657', 'Project Engineer', false, 'https://www.linkedin.com/in/octaviosoria/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Octavio Soria' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Hien Bui', c.id, 'PM', '(712) 255-0657', 'Project Engineer', false, 'https://www.linkedin.com/in/hien-bui-58560a210/', 'Sioux City', 'IA' FROM companies c WHERE c.name='L & L Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Hien Bui' AND company_id=c.id);
