-- 00046_seed_national_gc_batch2.sql
-- Seed national GCs batch 2: 11 companies + 98 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line (NOT NULL constraint).
-- "Walbridge" (OH) is a CITY for Rudolph Libbe Group, not the GC company "Walbridge".

-- ============================================================
-- COMPANIES (11)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'The Austin Company', 'GC', 'OH', 'Cleveland, OH', '(440) 544-2600', 'https://www.theaustin.com', 'Cleveland', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'The Austin Company');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Stellar', 'GC', 'FL', 'Jacksonville, FL', '(904) 260-2900', 'https://www.stellar.net', 'Jacksonville', 'FL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Stellar');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Shambaugh & Son', 'GC', 'IN', 'Fort Wayne, IN', '(260) 487-7777', 'https://www.shambaugh.com', 'Fort Wayne', 'IN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Shambaugh & Son');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'CRB', 'GC', 'MO', 'Kansas City, MO', '(816) 880-9800', 'https://www.crbgroup.com', 'Kansas City', 'MO' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'CRB');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Haskell', 'GC', 'FL', 'Jacksonville, FL', '(904) 791-4500', 'https://www.haskell.com', 'Jacksonville', 'FL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Haskell');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Graycor', 'GC', 'IL', 'Oakbrook Terrace, IL', '(630) 684-7110', 'https://www.graycor.com', 'Oakbrook Terrace', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Graycor');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Ryan Companies', 'GC', 'MN', 'Minneapolis, MN', '(612) 492-4000', 'https://www.ryancompanies.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Ryan Companies');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Alston Construction', 'GC', 'CA', 'Sacramento, CA', '(916) 340-2400', 'https://www.alstonco.com', 'Sacramento', 'CA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Alston Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'SSOE Group', 'GC', 'OH', 'Toledo, OH', '(419) 255-3830', 'https://www.ssoe.com', 'Toledo', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'SSOE Group');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Rudolph Libbe Group', 'GC', 'OH', 'Walbridge, OH', '(419) 241-5000', 'https://www.rlgbuilds.com', 'Walbridge', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Rudolph Libbe Group');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'DPR Construction', 'GC', 'CA', 'Redwood City, CA', '(650) 474-1450', 'https://www.dpr.com', 'Redwood City', 'CA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'DPR Construction');

-- ============================================================
-- CONTACTS (98)
-- ============================================================

-- The Austin Company (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris Jackson', c.id, 'ESTIMATOR', '(440) 544-2600', 'Vice President of Preconstruction', true, 'https://www.linkedin.com/in/chris-jiang3696859/', 'Cleveland', 'OH' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Jackson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Larry Dobson', c.id, 'ESTIMATOR', '(440) 544-2600', 'Supervisory Preconstruction Manager', false, 'https://www.linkedin.com/in/larry-dobson-b3603361/', 'Chardon', 'OH' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Larry Dobson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Amanda Mason', c.id, 'ESTIMATOR', '(440) 544-2600', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/amandamason5/', 'Kalamazoo', 'MI' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Amanda Mason' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matthew Lyster', c.id, 'PM', '(440) 544-2600', 'Construction Manager', false, 'https://www.linkedin.com/in/matthew-lyster-cpc-73590163/', 'Kalamazoo', 'MI' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Lyster' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nithesh Subramanyam', c.id, 'PM', '(440) 544-2600', 'Assistant Project Manager', false, 'https://www.linkedin.com/in/nithesh-subramanyam-125265117/', 'Kalamazoo', 'MI' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nithesh Subramanyam' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'DeAndria Porter', c.id, 'ESTIMATOR', '(440) 544-2600', 'Preconstruction Coordinator', false, 'https://www.linkedin.com/in/deandria-porter-78714498/', 'Cleveland', 'OH' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='DeAndria Porter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Daniel Guesman', c.id, 'PM', '(440) 544-2600', 'Director of Construction', true, 'https://www.linkedin.com/in/daniel-guesman-aic-cpc-38bb353b/', 'Melbourne', 'FL' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Guesman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Daniel Del Angel', c.id, 'PURCHASING', '(440) 544-2600', 'Procurement Lead', false, 'https://www.linkedin.com/in/daniel-del-angel-b22b0a61/', 'San Luis Potosi', 'MX' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Daniel Del Angel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Robert Wang', c.id, 'PM', '(440) 544-2600', 'Project Executive', true, 'https://www.linkedin.com/in/robert-wang-759b1761/', 'Orange County', 'CA' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Wang' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nirav Mehta', c.id, 'PM', '(440) 544-2600', 'Senior Project Manager', false, 'https://www.linkedin.com/in/nirav-mehta/', 'Irvine', 'CA' FROM companies c WHERE c.name='The Austin Company' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nirav Mehta' AND company_id=c.id);

-- Stellar (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Frank Lightfoot', c.id, 'PM', '(904) 260-2900', 'Project Executive', true, 'https://www.linkedin.com/in/flightfoot/', 'St. Augustine', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Frank Lightfoot' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Trey Mellon', c.id, 'ESTIMATOR', '(904) 260-2900', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/trey-mellon-481601143/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Trey Mellon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ken Warren', c.id, 'PM', '(904) 260-2900', 'Process Engineering Project Manager', false, 'https://www.linkedin.com/in/ken-warren-coffee/', 'Indianapolis', 'IN' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ken Warren' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mark Kraft', c.id, 'PM', '(904) 260-2900', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/mark-kraft-15627817/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mark Kraft' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Scott Wright', c.id, 'PM', '(904) 260-2900', 'Senior Project Manager', false, 'https://www.linkedin.com/in/scott-wright-61261415/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Wright' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tom Cramer', c.id, 'PM', '(904) 260-2900', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/tom-cramer-51399a33/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tom Cramer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Goode', c.id, 'PM', '(904) 260-2900', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jason-goode-07351112/', 'Wausau', 'WI' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Goode' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tyler Netting', c.id, 'PM', '(904) 260-2900', 'Project Manager III', false, 'https://www.linkedin.com/in/tyler-netting-17b11993/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Stellar' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Netting' AND company_id=c.id);

-- Shambaugh & Son (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matt Schmucker', c.id, 'ESTIMATOR', '(260) 487-7777', 'Senior Sales Estimator / Project Manager', false, 'https://www.linkedin.com/in/matt-schmucker-87251759/', 'Southfield', 'MI' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matt Schmucker' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Charlie Pavelec', c.id, 'PURCHASING', '(260) 487-7777', 'Sr. VP Purchasing', true, 'https://www.linkedin.com/in/charlie-pavelec-7a902412/', 'Fort Wayne', 'IN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Charlie Pavelec' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Sahsha Tigulis', c.id, 'PURCHASING', '(260) 487-7777', 'VP of Purchasing', true, 'https://www.linkedin.com/in/sahsha-tigulis-016b237/', 'Fort Wayne', 'IN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sahsha Tigulis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Nick Sorg', c.id, 'ESTIMATOR', '(260) 487-7777', 'Senior Estimator', false, 'https://www.linkedin.com/in/nick-sorg-27b15b30/', 'Fort Wayne', 'IN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Sorg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Reeves Callaway', c.id, 'ESTIMATOR', '(260) 487-7777', 'Contract Sales Estimator', false, 'https://www.linkedin.com/in/reeves-callaway-1b53958a/', 'Memphis', 'TN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Reeves Callaway' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Neuman', c.id, 'PM', '(260) 487-7777', 'Division Manager', true, 'https://www.linkedin.com/in/brian-neuman-66038442/', 'Greenwood', 'IN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Neuman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jonas Smith', c.id, 'PM', '(260) 487-7777', 'Project Manager', false, 'https://www.linkedin.com/in/jonas-smith-697859181/', 'Fort Wayne', 'IN' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jonas Smith' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Paul Young', c.id, 'PM', '(260) 487-7777', 'Sales Representative / Project Manager', false, 'https://www.linkedin.com/in/paul-young-34525418/', 'Bowling Green', 'OH' FROM companies c WHERE c.name='Shambaugh & Son' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Paul Young' AND company_id=c.id);

-- CRB (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris Bailey', c.id, 'ESTIMATOR', '(816) 880-9800', 'Senior Director / Chief Estimator', true, 'https://www.linkedin.com/in/chris-bailey-frics-925ab88/', 'Cranbury', 'NJ' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Bailey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Barrett', c.id, 'PM', '(816) 880-9800', 'Vice President, Global Project Delivery', true, 'https://www.linkedin.com/in/mike-barrett-29890710/', 'Cary', 'NC' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Barrett' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kory Kaplan', c.id, 'PM', '(816) 880-9800', 'Project Executive, Associate', true, 'https://www.linkedin.com/in/kory-kaplan-39a26211/', 'San Francisco', 'CA' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kory Kaplan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brandon Weiner', c.id, 'PM', '(816) 880-9800', 'Project Executive', true, 'https://www.linkedin.com/in/brandon-weiner-3a650424/', 'Atlanta', 'GA' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Weiner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matthew Lantzy', c.id, 'PM', '(816) 880-9800', 'Senior Project Director', true, 'https://www.linkedin.com/in/matthew-lantzy-71a32818/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Lantzy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris Callura', c.id, 'PM', '(816) 880-9800', 'Project Director', true, 'https://www.linkedin.com/in/chris-callura/', 'Arvada', 'CO' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Callura' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rob Couton', c.id, 'PM', '(816) 880-9800', 'Sr. Project Manager, Construction Group Lead - TX', false, 'https://www.linkedin.com/in/rob-couton-a1247415/', 'Keller', 'TX' FROM companies c WHERE c.name='CRB' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rob Couton' AND company_id=c.id);

-- Haskell (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Guy Stenzel', c.id, 'ESTIMATOR', '(904) 791-4500', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/guy-stenzel-0aa230a3/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Guy Stenzel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Adrienne Walley', c.id, 'ESTIMATOR', '(904) 791-4500', 'Senior Preconstruction Manager', false, 'https://www.linkedin.com/in/adrienne-freeman-68040755/', 'Roswell', 'GA' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adrienne Walley' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Atta Azeem', c.id, 'ESTIMATOR', '(904) 791-4500', 'Chief Estimator', true, 'https://www.linkedin.com/in/atta-azeem-mba-pmp-lean-6%CF%83-20813314/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Atta Azeem' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Sean Chapman', c.id, 'PURCHASING', '(904) 791-4500', 'Senior Manager, Strategic Sourcing', false, 'https://www.linkedin.com/in/sean-chapman-54b3645/', 'Tallahassee', 'FL' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sean Chapman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Russ Grinwis', c.id, 'PM', '(904) 791-4500', 'Director of Construction', true, 'https://www.linkedin.com/in/russ-grinwis-304521157/', 'Frisco', 'TX' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Russ Grinwis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brett White', c.id, 'PM', '(904) 791-4500', 'Director of Construction II', true, 'https://www.linkedin.com/in/brettjwhite/', 'Atlanta', 'GA' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brett White' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Richard Gomez', c.id, 'PM', '(904) 791-4500', 'Director - Project Executive', true, 'https://www.linkedin.com/in/richard-gomez4/', 'Dallas', 'TX' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Richard Gomez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Denise Muth', c.id, 'PM', '(904) 791-4500', 'Sr. Project Director', true, 'https://www.linkedin.com/in/denise-muth-63133533/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Denise Muth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Hulsey', c.id, 'PM', '(904) 791-4500', 'Senior Project Manager', false, 'https://www.linkedin.com/in/jason-hulsey-2669395b/', 'Jacksonville', 'FL' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Hulsey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Damian Etchison', c.id, 'PM', '(904) 791-4500', 'Senior Project Manager', false, 'https://www.linkedin.com/in/damian-m-etchison-15b36b8/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Haskell' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Damian Etchison' AND company_id=c.id);

-- Graycor (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'William Feldt', c.id, 'ESTIMATOR', '(630) 684-7110', 'Chief Estimator', true, 'https://www.linkedin.com/in/william-feldt-22a60a28/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='William Feldt' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Sylvester Gasiorek', c.id, 'ESTIMATOR', '(630) 684-7110', 'Sr. Preconstruction Estimator', false, 'https://www.linkedin.com/in/sylvester-gasiorek-mba-140b0116/', 'Chicago', 'IL' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sylvester Gasiorek' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brianna Lincoln', c.id, 'ESTIMATOR', '(630) 684-7110', 'PreConstruction Estimator II', false, 'https://www.linkedin.com/in/brianna-lincoln-65308248/', 'Scottsdale', 'AZ' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brianna Lincoln' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Drew Dye', c.id, 'ESTIMATOR', '(630) 684-7110', 'Preconstruction Estimator', false, 'https://www.linkedin.com/in/bailey-dye-22032a196/', 'Monroe', 'NC' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Drew Dye' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Max Burke', c.id, 'ESTIMATOR', '(630) 684-7110', 'Senior Estimator', false, 'https://www.linkedin.com/in/max-burke-ab527b63/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Max Burke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Zach Hawke', c.id, 'PM', '(630) 684-7110', 'Project Executive', true, 'https://www.linkedin.com/in/zach-hawke-58756a72/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Zach Hawke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Denbo', c.id, 'PM', '(630) 684-7110', 'Project Executive', true, 'https://www.linkedin.com/in/john-m-denbo-leed-green-associate-8b82416/', NULL, NULL FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Denbo' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Steve Crowley', c.id, 'PM', '(630) 684-7110', 'Construction Manager', false, 'https://www.linkedin.com/in/steve-crowley-5a8a2912/', 'St. John', 'IN' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steve Crowley' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Matthew Bero', c.id, 'PM', '(630) 684-7110', 'Senior Project Manager (Pharma)', false, 'https://www.linkedin.com/in/matthew-bero-68057731/', 'Villa Park', 'IL' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Bero' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Christopher Yates', c.id, 'PM', '(630) 684-7110', 'Project Manager II', false, 'https://www.linkedin.com/in/christophersamuelyates/', 'Oak Park', 'IL' FROM companies c WHERE c.name='Graycor' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher Yates' AND company_id=c.id);

-- Ryan Companies (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Paul Kieffer', c.id, 'ESTIMATOR', '(612) 492-4000', 'Vice President of Preconstruction Services', true, 'https://www.linkedin.com/in/paulkieffer/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Paul Kieffer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Petersen', c.id, 'ESTIMATOR', '(612) 492-4000', 'Vice President of Preconstruction - Housing', true, 'https://www.linkedin.com/in/john-petersen-658b5a7/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Petersen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brad Bakel', c.id, 'ESTIMATOR', '(612) 492-4000', 'Director of Preconstruction', true, 'https://www.linkedin.com/in/bradbakel/', 'Denver', 'CO' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brad Bakel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Avinash Shevelly', c.id, 'ESTIMATOR', '(612) 492-4000', 'Pre Construction Manager', false, 'https://www.linkedin.com/in/avinashshevelly/', 'Dallas-Fort Worth', 'TX' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Avinash Shevelly' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Taryn Ritchie', c.id, 'ESTIMATOR', '(612) 492-4000', 'Senior Estimator', false, 'https://www.linkedin.com/in/taryn-ritchie-66a673b/', 'Austin', 'TX' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Taryn Ritchie' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Anna Griffin', c.id, 'PM', '(612) 492-4000', 'Director of Construction', true, 'https://www.linkedin.com/in/anna-griffin-pmp-222a3b131/', NULL, NULL FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Anna Griffin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Bill Scherling', c.id, 'PM', '(612) 492-4000', 'Senior Project Executive', true, 'https://www.linkedin.com/in/bill-scherling-60757915/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bill Scherling' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eric Overgard', c.id, 'PM', '(612) 492-4000', 'Senior Project Executive', true, 'https://www.linkedin.com/in/eric-overgard-0a455613/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Overgard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Andy Assman', c.id, 'PM', '(612) 492-4000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/andy-assman-87132545/', 'Minneapolis', 'MN' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andy Assman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Lance Guerzon', c.id, 'PM', '(612) 492-4000', 'Senior Project Manager - Mission Critical', false, 'https://www.linkedin.com/in/lance-guerzon-09823725/', 'Milwaukee', 'WI' FROM companies c WHERE c.name='Ryan Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lance Guerzon' AND company_id=c.id);

-- Alston Construction (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Hennie van Niekerk', c.id, 'ESTIMATOR', '(916) 340-2400', 'Preconstruction Director', true, 'https://www.linkedin.com/in/henniev79/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Hennie van Niekerk' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Colin Moss', c.id, 'ESTIMATOR', '(916) 340-2400', 'Preconstruction Director', true, 'https://www.linkedin.com/in/colin-moss-leed-ap-1331879/', 'Downers Grove', 'IL' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Colin Moss' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tom Degan', c.id, 'PM', '(916) 340-2400', 'VP of Cold Storage', true, 'https://www.linkedin.com/in/tomdegan/', 'Chicago', 'IL' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tom Degan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Slinko', c.id, 'ESTIMATOR', '(916) 340-2400', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/mike-slinko-927a4b7/', 'Allentown', 'PA' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Slinko' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Lane McKibben', c.id, 'ESTIMATOR', '(916) 340-2400', 'Preconstruction Manager', false, 'https://www.linkedin.com/in/lmckibben/', 'Pontotoc', 'MS' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lane McKibben' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eric Kantorik', c.id, 'ESTIMATOR', '(916) 340-2400', 'Sr. Estimator', false, 'https://www.linkedin.com/in/erickantorik/', 'Nashville', 'TN' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Kantorik' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Probst', c.id, 'PM', '(916) 340-2400', 'Project Executive', true, 'https://www.linkedin.com/in/brian-probst-3b44799b/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Probst' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Mangini', c.id, 'PM', '(916) 340-2400', 'Project Director', true, 'https://www.linkedin.com/in/manginijohn/', 'Hilliard', 'OH' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Mangini' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jason Baird', c.id, 'PM', '(916) 340-2400', 'Project Director - Amazon BU', true, 'https://www.linkedin.com/in/jason-baird-84550a13/', 'Sacramento', 'CA' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Baird' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Wes Wooldridge', c.id, 'PM', '(916) 340-2400', 'Project Executive', true, 'https://www.linkedin.com/in/wes-wooldridge-9810864/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='Alston Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Wes Wooldridge' AND company_id=c.id);

-- SSOE Group (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Michael Lozier', c.id, 'ESTIMATOR', '(419) 255-3830', 'Senior Estimator / Project Controls', false, 'https://www.linkedin.com/in/michael-lozier-5b407011/', 'Toledo', 'OH' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Lozier' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jamie Locke', c.id, 'PM', '(419) 255-3830', 'Project Director, EPCM', true, 'https://www.linkedin.com/in/jamielockepmp/', 'Beaverton', 'OR' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jamie Locke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Scott Coe', c.id, 'PM', '(419) 255-3830', 'Department Manager - Automotive Project Management', true, 'https://www.linkedin.com/in/scott-coe-b233a717/', 'Brentwood', 'TN' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Scott Coe' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Eliut Granados', c.id, 'SUPER', '(419) 255-3830', 'Construction Site Manager', false, 'https://www.linkedin.com/in/eliut-granados-06660449/', 'Atlanta', 'GA' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eliut Granados' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ed Gerken', c.id, 'PM', '(419) 255-3830', 'Senior Project Manager', false, 'https://www.linkedin.com/in/edgerken/', 'Toledo', 'OH' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ed Gerken' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Dean Scheckelhoff', c.id, 'PM', '(419) 255-3830', 'Sr. Project Manager', false, 'https://www.linkedin.com/in/dean-l-scheckelhoff-96217b18/', 'Toledo', 'OH' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dean Scheckelhoff' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Weinbrecht', c.id, 'PM', '(419) 255-3830', 'Project Manager', false, 'https://www.linkedin.com/in/david-weinbrecht-4614baa1/', 'Toledo', 'OH' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Weinbrecht' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Paul Mohr', c.id, 'PM', '(419) 255-3830', 'Senior Engineering Project Manager', false, 'https://www.linkedin.com/in/paul-mohr-15533b61/', 'Waterville', 'OH' FROM companies c WHERE c.name='SSOE Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Paul Mohr' AND company_id=c.id);

-- Rudolph Libbe Group (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Troy Fritch', c.id, 'ESTIMATOR', '(419) 241-5000', 'Director, Preconstruction', true, 'https://www.linkedin.com/in/troy-fritch-5033062b/', 'North Ridgeville', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Troy Fritch' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Knab', c.id, 'ESTIMATOR', '(419) 241-5000', 'Preconstruction Leader', false, 'https://www.linkedin.com/in/david-knab-56376750/', 'Westlake', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Knab' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Steven Bruning', c.id, 'ESTIMATOR', '(419) 241-5000', 'Preconstruction Leader', false, 'https://www.linkedin.com/in/steven-bruning-469a93106/', 'Cleveland', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Bruning' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brandon Boehm', c.id, 'ESTIMATOR', '(419) 241-5000', 'Preconstruction Leader', false, 'https://www.linkedin.com/in/brandonboehm/', 'Toledo', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Boehm' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Bob Briggs', c.id, 'ESTIMATOR', '(419) 241-5000', 'Pre Construction Estimator', false, 'https://www.linkedin.com/in/bob-briggs-886a641bb/', 'Northwood', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bob Briggs' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Zach Eyssen', c.id, 'ESTIMATOR', '(419) 241-5000', 'Preconstruction Engineer', false, 'https://www.linkedin.com/in/zach-eyssen/', 'Brunswick', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Zach Eyssen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Darrell Boldt', c.id, 'PM', '(419) 241-5000', 'Sales / Project Manager', false, 'https://www.linkedin.com/in/darrell-buck-boldt-4aa66b54/', 'Ortonville', 'MI' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Darrell Boldt' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jamie Generous', c.id, 'PM', '(419) 241-5000', 'Project Manager', false, 'https://www.linkedin.com/in/jamie-generous-95a50637/', 'Hartland', 'MI' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jamie Generous' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brian Swope', c.id, 'PM', '(419) 241-5000', 'Senior Project Manager', false, 'https://www.linkedin.com/in/brian-swope-ccm-b456b16/', 'Bowling Green', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Swope' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kurt McKee', c.id, 'PM', '(419) 241-5000', 'Project Manager', false, 'https://www.linkedin.com/in/kurt-mckee-6304796a/', 'Toledo', 'OH' FROM companies c WHERE c.name='Rudolph Libbe Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kurt McKee' AND company_id=c.id);

-- DPR Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Josh Vallimont', c.id, 'PM', '(650) 474-1450', 'Project Executive', true, 'https://www.linkedin.com/in/josh-vallimont-51052411/', 'Charlotte', 'NC' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Vallimont' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Brad Procz', c.id, 'ESTIMATOR', '(650) 474-1450', 'Estimator', false, 'https://www.linkedin.com/in/brad-procz-608a6394/', 'Philadelphia', 'PA' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brad Procz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Wei Huang', c.id, 'PURCHASING', '(650) 474-1450', 'Supplier Sourcing & Relationship Leader', false, 'https://www.linkedin.com/in/weihuang108/', 'San Francisco', 'CA' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Wei Huang' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Joseph Opyd', c.id, 'PM', '(650) 474-1450', 'Sr. Project Manager / Project Controls Manager', false, 'https://www.linkedin.com/in/joseph-opyd-dbia-ccm-a70335b/', 'Colorado Springs', 'CO' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joseph Opyd' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Avinash Damera', c.id, 'PM', '(650) 474-1450', 'Senior Project Manager', false, 'https://www.linkedin.com/in/avinashdamera/', 'Irving', 'TX' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Avinash Damera' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kris Sims', c.id, 'PM', '(650) 474-1450', 'Senior Project Manager', false, 'https://www.linkedin.com/in/kris-sims-7090378a/', 'Dallas-Fort Worth', 'TX' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kris Sims' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'John Parker Hawkins', c.id, 'PM', '(650) 474-1450', 'Project Manager', false, 'https://www.linkedin.com/in/john-parker-hawkins-5a84a448/', 'Raleigh', 'NC' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Parker Hawkins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Luke Vaughn', c.id, 'PM', '(650) 474-1450', 'Project Manager', false, 'https://www.linkedin.com/in/luke-vaughn-0492a381/', 'Washington', 'DC' FROM companies c WHERE c.name='DPR Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Luke Vaughn' AND company_id=c.id);
