-- 00054_rename_owner_and_seed_facility_buyers.sql
-- Part A: Rename company_type enum 'PLANT_OWNER' → 'OWNER' (PG 10+ RENAME VALUE).
-- Part B: Seed 9 facility-owner companies (type OWNER) + 38 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = NULL (no company lines in this batch; phone is NOT NULL so we use empty string).

-- ============================================================
-- PART A: ENUM RENAME
-- ============================================================
ALTER TYPE company_type RENAME VALUE 'PLANT_OWNER' TO 'OWNER';

-- ============================================================
-- PART B: COMPANIES (9)
-- ============================================================
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Flynn Group', 'OWNER', 'OH', 'Independence, OH', 'Independence', 'OH' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Flynn Group');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Carrols Corporation', 'OWNER', 'KY', 'Crestwood, KY', 'Crestwood', 'KY' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Carrols Corporation');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Dhanani / Tri City Foods', 'OWNER', 'IL', 'Grayslake, IL', 'Grayslake', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Dhanani / Tri City Foods');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Sun Holdings', 'OWNER', 'TX', 'Dallas, TX', 'Dallas', 'TX' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Sun Holdings');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'McDonald''s', 'OWNER', 'IL', 'Chicago, IL', 'Chicago', 'IL' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'McDonald''s');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Waffle House', 'OWNER', 'GA', 'Dacula, GA', 'Dacula', 'GA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Waffle House');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Starbucks', 'OWNER', 'WA', 'Seattle, WA', 'Seattle', 'WA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Starbucks');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Inspire Brands', 'OWNER', 'GA', 'Atlanta, GA', 'Atlanta', 'GA' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Inspire Brands');
INSERT INTO companies (name, type, region, address, city, state) SELECT 'Circle K', 'OWNER', 'AZ', 'Tempe, AZ', 'Tempe', 'AZ' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Circle K');

-- ============================================================
-- CONTACTS (38) — role PM (placeholder), phone NOT NULL so use empty string
-- ============================================================

-- Flynn Group (4)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Lisa Perman', c.id, 'PM', '', 'VP of Construction', true, 'https://www.linkedin.com/in/lisa-perman-5b58828/', 'Independence', 'OH' FROM companies c WHERE c.name='Flynn Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lisa Perman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kevin Walter', c.id, 'PM', '', 'Director of Construction', true, 'https://www.linkedin.com/in/kevin-l-walter/', 'Strongsville', 'OH' FROM companies c WHERE c.name='Flynn Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kevin Walter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Yasemin Sarier', c.id, 'PM', '', 'Director of Construction', true, 'https://www.linkedin.com/in/yasemin-sarier-816298/', NULL, NULL FROM companies c WHERE c.name='Flynn Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Yasemin Sarier' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Michael Beinhauer', c.id, 'PM', '', 'Director of Facilities Management', true, 'https://www.linkedin.com/in/michael-beinhauer-8b64a49a/', 'Odessa', 'FL' FROM companies c WHERE c.name='Flynn Group' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Beinhauer' AND company_id=c.id);

-- Carrols Corporation (2)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tim McIntyre', c.id, 'PM', '', 'Construction Manager', false, 'https://www.linkedin.com/in/tim-mcintyre-89331216/', 'Crestwood', 'KY' FROM companies c WHERE c.name='Carrols Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tim McIntyre' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Gerry Padden', c.id, 'PM', '', 'Construction Manager', false, 'https://www.linkedin.com/in/gerry-padden-7a97b5126/', 'Cary', 'NC' FROM companies c WHERE c.name='Carrols Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Gerry Padden' AND company_id=c.id);

-- Dhanani / Tri City Foods (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jeffrey MacDonald', c.id, 'PM', '', 'Executive Director of Facilities/Development', true, 'https://www.linkedin.com/in/jeffrey-macdonald-1a6b7053/', 'Grayslake', 'IL' FROM companies c WHERE c.name='Dhanani / Tri City Foods' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jeffrey MacDonald' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jay McGinn', c.id, 'PM', '', 'Facilities/Construction Manager', false, 'https://www.linkedin.com/in/jay-mcginn-67912349/', 'Libertyville', 'IL' FROM companies c WHERE c.name='Dhanani / Tri City Foods' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jay McGinn' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Pam Mankowski Flores', c.id, 'PM', '', 'Facilities Maintenance Manager', false, 'https://www.linkedin.com/in/pam-mankowski-flores-5a29229b/', 'Tinley Park', 'IL' FROM companies c WHERE c.name='Dhanani / Tri City Foods' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pam Mankowski Flores' AND company_id=c.id);

-- Sun Holdings (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Armando Palacios', c.id, 'PM', '', 'Director of Construction', true, 'https://www.linkedin.com/in/armando-palacios-158a359b/', 'Dallas', 'TX' FROM companies c WHERE c.name='Sun Holdings' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Armando Palacios' AND company_id=c.id);

-- McDonald's (14)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Michele Miller', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/michele-miller-b264b14b/', 'Akron', 'OH' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michele Miller' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kim Ernest', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/kim-ernest-b467a111/', 'Fort Lauderdale', 'FL' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kim Ernest' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Elizabeth Chadwick', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/elizabeth-chadwick-847b26132/', 'Long Beach', 'CA' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Elizabeth Chadwick' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mikel Eldredge', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/mikel-eldredge-b7420675/', 'Spring', 'TX' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mikel Eldredge' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Robin Geotina', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/robin-geotina/', 'Seattle', 'WA' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robin Geotina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Steven Ruffino', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/steven-ruffino-8baa2bab/', 'New York', 'NY' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Ruffino' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Josh Gatewood', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/josh-gatewood-csi-cdt-04379928/', 'Kansas City', 'MO' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Gatewood' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jim Lyon', c.id, 'PM', '', 'Area Construction Manager', false, 'https://www.linkedin.com/in/jamesllyon/', 'Frisco', 'TX' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Lyon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Lee Morris', c.id, 'PM', '', 'Regional Construction Manager', true, 'https://www.linkedin.com/in/lee-morris-43a56113/', NULL, NULL FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lee Morris' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Kevin McAuley', c.id, 'PM', '', 'Construction Manager', false, 'https://www.linkedin.com/in/kevin-mcauley-0a733a90/', 'Las Vegas', 'NV' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kevin McAuley' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Trevor Prophet', c.id, 'PM', '', 'Construction Manager', false, 'https://www.linkedin.com/in/trevor-prophet-599a3747/', 'Denver', 'CO' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Trevor Prophet' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Chris Stepp', c.id, 'PM', '', 'Construction Manager', false, 'https://www.linkedin.com/in/chris-stepp-80181979/', 'Kenosha', 'WI' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Stepp' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jesse Stiles', c.id, 'PM', '', 'Director of Real Estate', true, 'https://www.linkedin.com/in/jesse-stiles-99960ba/', 'Phoenix', 'AZ' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jesse Stiles' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Jaysan Stevanovich', c.id, 'PM', '', 'Facilities Supervisor', false, 'https://www.linkedin.com/in/jaysanstevanovich/', 'Chicago', 'IL' FROM companies c WHERE c.name='McDonald''s' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jaysan Stevanovich' AND company_id=c.id);

-- Waffle House (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'David Mitchell', c.id, 'PM', '', 'VP Construction', true, 'https://www.linkedin.com/in/david-mitchell-b2364018/', 'Dacula', 'GA' FROM companies c WHERE c.name='Waffle House' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Mitchell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mercedes Field', c.id, 'PM', '', 'Director of Real Estate Strategy & Property Mgmt', true, 'https://www.linkedin.com/in/mercedes-field/', 'Jefferson', 'GA' FROM companies c WHERE c.name='Waffle House' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mercedes Field' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Tyler Schuster', c.id, 'PM', '', 'Real Estate Director', true, 'https://www.linkedin.com/in/tyler-schuster-a61a55126/', 'Norcross', 'GA' FROM companies c WHERE c.name='Waffle House' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Schuster' AND company_id=c.id);

-- Starbucks (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Valerie Schoenholtz', c.id, 'PM', '', 'Sr. Facilities Manager', false, 'https://www.linkedin.com/in/valerie-schoenholtz-7b80111a/', 'Miami-Fort Lauderdale', 'FL' FROM companies c WHERE c.name='Starbucks' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Valerie Schoenholtz' AND company_id=c.id);

-- Inspire Brands (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Volker Heimeshoff', c.id, 'PM', '', 'VP Construction', true, 'https://www.linkedin.com/in/volker-heimeshoff-94b4aa10/', 'Bentonville', 'AR' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Volker Heimeshoff' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Ryan Garcia', c.id, 'PM', '', 'Director of Facilities', true, 'https://www.linkedin.com/in/ryan-garcia-03a265b5/', NULL, NULL FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Garcia' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Fred Sigmund', c.id, 'PM', '', 'Director of Facilities Management', true, 'https://www.linkedin.com/in/fred-sigmund-56b9b3a/', 'Atlanta', 'GA' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Fred Sigmund' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Rob Lalumia', c.id, 'PM', '', 'Director of Construction', true, 'https://www.linkedin.com/in/rob-lalumia-38071a6/', 'Charleston', 'SC' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rob Lalumia' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Lissette Gonzalez', c.id, 'PM', '', 'Director of Construction - Corporate Portfolio', true, 'https://www.linkedin.com/in/lissettegonzalez09/', 'Charlotte', 'NC' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lissette Gonzalez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Alisa Rynek', c.id, 'PM', '', 'Director of Construction Services', true, 'https://www.linkedin.com/in/alisa-rynek-bab20142/', 'Canton', 'MA' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alisa Rynek' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Charles DeFiglio', c.id, 'PM', '', 'Sr. Director of Real Estate', true, 'https://www.linkedin.com/in/charles-defiglio-31930611/', 'Lanoka Harbor', 'NJ' FROM companies c WHERE c.name='Inspire Brands' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Charles DeFiglio' AND company_id=c.id);

-- Circle K (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Renan Serafim', c.id, 'PM', '', 'Director of Facilities, Construction & Environmental', true, 'https://www.linkedin.com/in/renan-serafim-mba-69a413b6/', 'Pensacola', 'FL' FROM companies c WHERE c.name='Circle K' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Renan Serafim' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Mike Higgins', c.id, 'PM', '', 'Director of Real Estate Development', true, 'https://www.linkedin.com/in/mike-higgins-20615ab1/', 'Tampa', 'FL' FROM companies c WHERE c.name='Circle K' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Higgins' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, linkedin_url, city, state) SELECT 'Joshua Swinford', c.id, 'PM', '', 'Director of Real Estate Development', true, 'https://www.linkedin.com/in/joshuaswinford/', 'Gulf Breeze', 'FL' FROM companies c WHERE c.name='Circle K' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joshua Swinford' AND company_id=c.id);
