-- 00055_seed_mn_gc_contacts.sql
-- Seed MN GCs: 9 new companies + contacts for 10 companies (including existing Greystone Construction).
-- Idempotent: skip company if name exists; skip contact if same name+company exists.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line. linkedin_url = NULL. city/state = company's.
-- Greystone Construction already exists (batch 1) — company insert skipped, contacts linked to existing row.
-- Existing Greystone contacts (David Hartman, Reed Baillargeon, Jim Bystrzycki, Christian Mertz, Brandon Gorder) will be skipped as dupes.

-- ============================================================
-- COMPANIES (9 new + 1 existing Greystone)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'RJM Construction', 'GC', 'MN', 'Minneapolis, MN', '(952) 837-8600', 'https://www.rjmconstruction.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'RJM Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Stahl Construction', 'GC', 'MN', 'Minneapolis, MN', '(952) 931-9300', 'https://www.stahlconstruction.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Stahl Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Greiner Construction', 'GC', 'MN', 'Minneapolis, MN', '(612) 338-1696', 'https://www.greinerconstruction.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Greiner Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Watson-Forsberg', 'GC', 'MN', 'Minneapolis, MN', '(952) 544-7761', 'https://www.watson-forsberg.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Watson-Forsberg');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Gardner Builders', 'GC', 'MN', 'Minneapolis, MN', '(612) 326-6377', 'https://www.gardner-builders.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Gardner Builders');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Shaw-Lundquist Associates', 'GC', 'MN', 'Eagan, MN', '(651) 454-0670', 'https://www.shawlundquist.com', 'Eagan', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Shaw-Lundquist Associates');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Rochon Corporation', 'GC', 'MN', 'Plymouth, MN', '(763) 559-9393', 'https://www.rochoncorp.com', 'Plymouth', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Rochon Corporation');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Ebert Companies', 'GC', 'MN', 'Corcoran, MN', '(763) 498-7844', 'https://www.ebertcompanies.com', 'Corcoran', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Ebert Companies');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Greystone Construction', 'GC', 'MN', 'Shakopee, MN', '(952) 496-2227', 'https://www.greystoneconstruction.com', 'Shakopee', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Greystone Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Met-Con Companies', 'GC', 'MN', 'Faribault, MN', '(507) 332-2266', 'https://www.met-con.com', 'Faribault', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Met-Con Companies');

-- ============================================================
-- CONTACTS
-- ============================================================

-- RJM Construction (16)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brian Pogalz', c.id, 'ESTIMATOR', '(952) 837-8600', 'Chief Estimator', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Pogalz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Isaac Lindberg', c.id, 'ESTIMATOR', '(952) 837-8600', 'Estimator III', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Isaac Lindberg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nick Driessen', c.id, 'ESTIMATOR', '(952) 837-8600', 'Estimator II', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Driessen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Curtis Sell', c.id, 'PM', '(952) 837-8600', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Curtis Sell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Dan Schultz', c.id, 'PM', '(952) 837-8600', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dan Schultz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Sam Sheehan', c.id, 'PM', '(952) 837-8600', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sam Sheehan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Kristopher Hahn', c.id, 'PM', '(952) 837-8600', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kristopher Hahn' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Bryce Kamenick', c.id, 'PM', '(952) 837-8600', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bryce Kamenick' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brad Barickman', c.id, 'PM', '(952) 837-8600', 'VP of Community Construction', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brad Barickman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Aaron Chappuis', c.id, 'PM', '(952) 837-8600', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Aaron Chappuis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Christopher Thurnbeck', c.id, 'PM', '(952) 837-8600', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christopher Thurnbeck' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Drew Suggs', c.id, 'PM', '(952) 837-8600', 'Project Manager II', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Drew Suggs' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ryan Potocnik', c.id, 'PM', '(952) 837-8600', 'Project Manager II', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Potocnik' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Juan Lopez', c.id, 'PM', '(952) 837-8600', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Juan Lopez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Blake Herdina', c.id, 'PM', '(952) 837-8600', 'Project Manager II', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Blake Herdina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Alexus Jackson', c.id, 'PM', '(952) 837-8600', 'Project Engineer', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='RJM Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alexus Jackson' AND company_id=c.id);

-- Stahl Construction (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Meghan Huber', c.id, 'PM', '(952) 931-9300', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Meghan Huber' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Deborah Aldrich', c.id, 'PM', '(952) 931-9300', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Deborah Aldrich' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Dave Schultz', c.id, 'PM', '(952) 931-9300', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dave Schultz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nicole Olson', c.id, 'PM', '(952) 931-9300', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nicole Olson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Derek Meyer', c.id, 'PM', '(952) 931-9300', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Derek Meyer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Timothy Fahey', c.id, 'PM', '(952) 931-9300', 'Assistant Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Timothy Fahey' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Kristy Casper', c.id, 'PM', '(952) 931-9300', 'Assistant Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Stahl Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kristy Casper' AND company_id=c.id);

-- Greiner Construction (14)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Austin Visina', c.id, 'ESTIMATOR', '(612) 338-1696', 'Senior Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Austin Visina' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Andy Pelzel', c.id, 'ESTIMATOR', '(612) 338-1696', 'Senior Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andy Pelzel' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Robert Dunleavy', c.id, 'PM', '(612) 338-1696', 'Principal', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Dunleavy' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Chris Bristow', c.id, 'PM', '(612) 338-1696', 'Construction Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Bristow' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Steve Amis', c.id, 'PM', '(612) 338-1696', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steve Amis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Robert Stenger', c.id, 'PM', '(612) 338-1696', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Stenger' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Joseph Higley', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joseph Higley' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nick Alms', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Alms' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'John Pupkes', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Pupkes' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jacob Machone', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Machone' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brian Mickschl', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Mickschl' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'A.J. Flagg', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='A.J. Flagg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Carl Krieger', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Carl Krieger' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Travis Melquist', c.id, 'PM', '(612) 338-1696', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Travis Melquist' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Aleisha Kiley', c.id, 'PM', '(612) 338-1696', 'Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Greiner Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Aleisha Kiley' AND company_id=c.id);

-- Watson-Forsberg (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Dave Carlson', c.id, 'ESTIMATOR', '(952) 544-7761', 'Project Executive - Preconstruction & Estimating', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dave Carlson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nate Robitschek', c.id, 'ESTIMATOR', '(952) 544-7761', 'Principal - Director of Preconstruction', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nate Robitschek' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'David Forsberg', c.id, 'PM', '(952) 544-7761', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Forsberg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Robert Forsberg', c.id, 'PM', '(952) 544-7761', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Robert Forsberg' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Paul Ogren', c.id, 'PM', '(952) 544-7761', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Paul Ogren' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Colby Salonek', c.id, 'PM', '(952) 544-7761', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Colby Salonek' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Lexa Isles', c.id, 'PM', '(952) 544-7761', 'Associate Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Watson-Forsberg' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Lexa Isles' AND company_id=c.id);

-- Gardner Builders (19)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Pete Schwarz', c.id, 'PM', '(612) 326-6377', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pete Schwarz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Randy LaFaive', c.id, 'PM', '(612) 326-6377', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Randy LaFaive' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brandon Abrahamson', c.id, 'PM', '(612) 326-6377', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Abrahamson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Mike Puncochar', c.id, 'PM', '(612) 326-6377', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mike Puncochar' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jordan Einck', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jordan Einck' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Katrina Porter', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Katrina Porter' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Spencer Crittendon', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Spencer Crittendon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nick Kosmides', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Kosmides' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Connor Hart', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Connor Hart' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Tyler Matson', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Matson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jen Merchlewitz', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jen Merchlewitz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Michael Beer', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Beer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jeff Loehmann', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jeff Loehmann' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Samuel Johnson', c.id, 'PM', '(612) 326-6377', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Samuel Johnson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Curtis Martinson', c.id, 'PM', '(612) 326-6377', 'Duluth Office Lead', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Curtis Martinson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Alison Kimber-Woody', c.id, 'PM', '(612) 326-6377', 'Senior Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alison Kimber-Woody' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brenna Hahnfeldt', c.id, 'PM', '(612) 326-6377', 'Senior Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brenna Hahnfeldt' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Kyle Frost', c.id, 'PM', '(612) 326-6377', 'Senior Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kyle Frost' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jen Wilson', c.id, 'PM', '(612) 326-6377', 'Lead Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Gardner Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jen Wilson' AND company_id=c.id);

-- Shaw-Lundquist Associates (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Chris James', c.id, 'ESTIMATOR', '(651) 454-0670', 'Director of Preconstruction', true, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris James' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Cory Jones', c.id, 'ESTIMATOR', '(651) 454-0670', 'Pre-Construction Estimator', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Cory Jones' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'John Meyers', c.id, 'ESTIMATOR', '(651) 454-0670', 'Senior Estimator', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Meyers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'David Meyers', c.id, 'ESTIMATOR', '(651) 454-0670', 'Senior Estimator / PM', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Meyers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Trent Lundquist', c.id, 'PM', '(651) 454-0670', 'Project Manager', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Trent Lundquist' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brandon Larson', c.id, 'PM', '(651) 454-0670', 'Project Manager', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Larson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Amy Santerre', c.id, 'PM', '(651) 454-0670', 'Project Manager', false, 'Eagan', 'MN' FROM companies c WHERE c.name='Shaw-Lundquist Associates' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Amy Santerre' AND company_id=c.id);

-- Rochon Corporation (11)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Stacy Gleason', c.id, 'PM', '(763) 559-9393', 'Senior Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Stacy Gleason' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Edward Dehmer', c.id, 'PM', '(763) 559-9393', 'Senior Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Edward Dehmer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jake Fischer', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jake Fischer' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Josh Seiler', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Josh Seiler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brandon Gray', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Gray' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Shanna Heard', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shanna Heard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Rob Erdman', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Rob Erdman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Corey Bokinskie', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Corey Bokinskie' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Steven Fox', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Fox' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jack Braton', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jack Braton' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jon Clark', c.id, 'PM', '(763) 559-9393', 'Project Manager', false, 'Plymouth', 'MN' FROM companies c WHERE c.name='Rochon Corporation' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon Clark' AND company_id=c.id);

-- Ebert Companies (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Zach Meschke', c.id, 'PM', '(763) 498-7844', 'Senior Project Manager', false, 'Corcoran', 'MN' FROM companies c WHERE c.name='Ebert Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Zach Meschke' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Keegan Adams', c.id, 'PM', '(763) 498-7844', 'Project Manager', false, 'Corcoran', 'MN' FROM companies c WHERE c.name='Ebert Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Keegan Adams' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Mathew Bentz', c.id, 'PM', '(763) 498-7844', 'Project Manager', false, 'Corcoran', 'MN' FROM companies c WHERE c.name='Ebert Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Mathew Bentz' AND company_id=c.id);

-- Greystone Construction (14 — 5 will be skipped as dupes from batch 1: David Hartman, Reed Baillargeon, Jim Bystrzycki, Christian Mertz, Brandon Gorder)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'David Hartman', c.id, 'ESTIMATOR', '(952) 496-2227', 'Preconstruction Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Hartman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Reed Baillargeon', c.id, 'ESTIMATOR', '(952) 496-2227', 'Estimator / Project Coordinator', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Reed Baillargeon' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jim Bystrzycki', c.id, 'PM', '(952) 496-2227', 'Senior Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Bystrzycki' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nick Jeurissen', c.id, 'PM', '(952) 496-2227', 'Senior Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nick Jeurissen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Hunter Factor', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Hunter Factor' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ben Damm', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ben Damm' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brian Kohlhof', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Kohlhof' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Christian Mertz', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christian Mertz' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Landon Karst', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Landon Karst' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Abby School', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Abby School' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Tanner Wisemiller', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tanner Wisemiller' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Elena Guastella', c.id, 'PM', '(952) 496-2227', 'Operations Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Elena Guastella' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brandon Gorder', c.id, 'PM', '(952) 496-2227', 'Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Gorder' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jessica Bollingmo', c.id, 'PM', '(952) 496-2227', 'Assistant Project Manager', false, 'Shakopee', 'MN' FROM companies c WHERE c.name='Greystone Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jessica Bollingmo' AND company_id=c.id);

-- Met-Con Companies (2)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Parker Beaupre', c.id, 'PM', '(507) 332-2266', 'Project Manager', false, 'Faribault', 'MN' FROM companies c WHERE c.name='Met-Con Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Parker Beaupre' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Casey Funk', c.id, 'PM', '(507) 332-2266', 'Project Manager', false, 'Faribault', 'MN' FROM companies c WHERE c.name='Met-Con Companies' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Casey Funk' AND company_id=c.id);
