-- 00056_seed_mn_gc_contacts_batch2.sql
-- Seed MN GCs batch 2: 10 companies + 72 contacts. Idempotent.
-- No owner_id on companies/contacts (shared reference data).
-- Contact phone = company main line. linkedin_url = NULL. city/state = company's.
-- Marcus Construction may already exist — company insert skipped if so, contacts linked to existing row.

-- ============================================================
-- COMPANIES (10)
-- ============================================================
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Weis Builders', 'GC', 'MN', 'Minneapolis, MN', '(612) 243-5000', 'https://www.weisbuilders.com', 'Minneapolis', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Weis Builders');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Donlar Construction', 'GC', 'MN', 'Saint Paul, MN', '(651) 227-0631', 'https://www.donlarcorp.com', 'Saint Paul', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Donlar Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Loeffler Construction', 'GC', 'MN', 'Lakeville, MN', '(952) 955-9119', 'https://www.loefflerconstruction.com', 'Lakeville', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Loeffler Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Sheehy Construction', 'GC', 'MN', 'Saint Paul, MN', '(651) 488-6691', 'https://www.sheehyconstruction.com', 'Saint Paul', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Sheehy Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Bauer Design Build', 'GC', 'MN', 'Rogers, MN', '(763) 972-0000', 'https://www.bauerdesignbuild.com', 'Rogers', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Bauer Design Build');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'LS Black Constructors', 'GC', 'MN', 'Saint Paul, MN', '(651) 774-8445', 'https://www.lsblack.com', 'Saint Paul', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'LS Black Constructors');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Shingobee Builders', 'GC', 'MN', 'Loretto, MN', '(763) 479-1300', 'https://www.shingobee.com', 'Loretto', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Shingobee Builders');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Marcus Construction', 'GC', 'MN', 'Willmar, MN', '(320) 222-6616', 'https://www.marcusconstruction.com', 'Willmar', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Marcus Construction');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Maertens-Brenny', 'GC', 'MN', 'Brooklyn Park, MN', '(763) 350-8762', 'https://www.maertensbrenny.com', 'Brooklyn Park', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Maertens-Brenny');
INSERT INTO companies (name, type, region, address, phone, website, city, state) SELECT 'Jorgenson Construction', 'GC', 'MN', 'Blaine, MN', '(763) 784-3877', 'https://www.jorgensonconstruction.com', 'Blaine', 'MN' WHERE NOT EXISTS (SELECT 1 FROM companies WHERE name = 'Jorgenson Construction');

-- ============================================================
-- CONTACTS (72)
-- ============================================================

-- Weis Builders (12)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brandon Treinen', c.id, 'ESTIMATOR', '(612) 243-5000', 'Preconstruction Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brandon Treinen' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nate Hopeman', c.id, 'ESTIMATOR', '(612) 243-5000', 'Preconstruction Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nate Hopeman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Andrew Neubarth', c.id, 'ESTIMATOR', '(612) 243-5000', 'Senior Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andrew Neubarth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Dan Melstrom', c.id, 'ESTIMATOR', '(612) 243-5000', 'Senior Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dan Melstrom' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'David Peterson', c.id, 'ESTIMATOR', '(612) 243-5000', 'Senior Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='David Peterson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Cole Bernhardson', c.id, 'ESTIMATOR', '(612) 243-5000', 'Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Cole Bernhardson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'San Hassan', c.id, 'ESTIMATOR', '(612) 243-5000', 'Assistant Estimator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='San Hassan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jason Law', c.id, 'PM', '(612) 243-5000', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Law' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Christian Haugh', c.id, 'PM', '(612) 243-5000', 'Project Executive', true, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Christian Haugh' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Adam Hannan', c.id, 'PM', '(612) 243-5000', 'Senior Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Hannan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jeffrey Jackson', c.id, 'PM', '(612) 243-5000', 'Project Manager', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jeffrey Jackson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ashley Myers', c.id, 'PM', '(612) 243-5000', 'Senior Project Coordinator', false, 'Minneapolis', 'MN' FROM companies c WHERE c.name='Weis Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ashley Myers' AND company_id=c.id);

-- Donlar Construction (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Stu Woodworth', c.id, 'ESTIMATOR', '(651) 227-0631', 'Chief Estimator', true, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Stu Woodworth' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Kurt Aldentaler', c.id, 'ESTIMATOR', '(651) 227-0631', 'Lead Estimator', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Kurt Aldentaler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Chris Osby', c.id, 'ESTIMATOR', '(651) 227-0631', 'Project Manager/Estimator', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Osby' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Tyler Lawry', c.id, 'PM', '(651) 227-0631', 'Senior Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Tyler Lawry' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Matthew Browne', c.id, 'PM', '(651) 227-0631', 'Senior Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Matthew Browne' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jon Polzin', c.id, 'PM', '(651) 227-0631', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jon Polzin' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nate Bell', c.id, 'PM', '(651) 227-0631', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nate Bell' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nicholas Siler', c.id, 'PM', '(651) 227-0631', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nicholas Siler' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jim Rothstein', c.id, 'PM', '(651) 227-0631', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Donlar Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jim Rothstein' AND company_id=c.id);

-- Loeffler Construction (8)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Drew Illetschko', c.id, 'ESTIMATOR', '(952) 955-9119', 'Project Estimator', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Drew Illetschko' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Eric Prettyman', c.id, 'ESTIMATOR', '(952) 955-9119', 'Construction Estimator', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Prettyman' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Zachary Ekstrom', c.id, 'ESTIMATOR', '(952) 955-9119', 'Estimator', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Zachary Ekstrom' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ben Nordquist', c.id, 'ESTIMATOR', '(952) 955-9119', 'Estimator / PM / Superintendent', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ben Nordquist' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Corey Myers', c.id, 'PM', '(952) 955-9119', 'Project Manager', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Corey Myers' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'John Barrick', c.id, 'PM', '(952) 955-9119', 'Project Manager', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='John Barrick' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brock Reese', c.id, 'PM', '(952) 955-9119', 'Project Manager', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brock Reese' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Cameron Dahlin', c.id, 'PM', '(952) 955-9119', 'Project Manager', false, 'Lakeville', 'MN' FROM companies c WHERE c.name='Loeffler Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Cameron Dahlin' AND company_id=c.id);

-- Sheehy Construction (7)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Danial Hannover', c.id, 'PM', '(651) 488-6691', 'Senior Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Danial Hannover' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Eric Matthews', c.id, 'PM', '(651) 488-6691', 'Vice President', true, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eric Matthews' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Blake Peterson', c.id, 'PM', '(651) 488-6691', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Blake Peterson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jacob Bruhn', c.id, 'PM', '(651) 488-6691', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Bruhn' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Adam Krause', c.id, 'PM', '(651) 488-6691', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Adam Krause' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ryan Stober', c.id, 'PM', '(651) 488-6691', 'Assistant Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ryan Stober' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Casey Stoll', c.id, 'PM', '(651) 488-6691', 'Assistant Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='Sheehy Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Casey Stoll' AND company_id=c.id);

-- Bauer Design Build (10)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Nate Gebert', c.id, 'PM', '(763) 972-0000', 'Senior Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Nate Gebert' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Corey Arones', c.id, 'PM', '(763) 972-0000', 'Senior Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Corey Arones' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Chad Bulera', c.id, 'PM', '(763) 972-0000', 'Senior Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chad Bulera' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Steve Leverington', c.id, 'PM', '(763) 972-0000', 'Senior Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steve Leverington' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jason Barrett', c.id, 'PM', '(763) 972-0000', 'Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jason Barrett' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Alec Albright', c.id, 'PM', '(763) 972-0000', 'Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alec Albright' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Alex Schmoll', c.id, 'PM', '(763) 972-0000', 'Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alex Schmoll' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Elijah Kracht', c.id, 'PM', '(763) 972-0000', 'Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Elijah Kracht' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Travis Helkamp', c.id, 'PM', '(763) 972-0000', 'Assistant Project Manager', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Travis Helkamp' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Sidney Knapp', c.id, 'PM', '(763) 972-0000', 'Project Coordinator', false, 'Rogers', 'MN' FROM companies c WHERE c.name='Bauer Design Build' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Sidney Knapp' AND company_id=c.id);

-- LS Black Constructors (12)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Chris Harchanko', c.id, 'ESTIMATOR', '(651) 774-8445', 'Director of Preconstruction', true, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Chris Harchanko' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Vital Brouillard', c.id, 'ESTIMATOR', '(651) 774-8445', 'Director of Preconstruction', true, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Vital Brouillard' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Katie Bollmeier', c.id, 'ESTIMATOR', '(651) 774-8445', 'Preconstruction Coordinator', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Katie Bollmeier' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jesse Anderson', c.id, 'PM', '(651) 774-8445', 'Senior Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jesse Anderson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Wilson Velasquez', c.id, 'PM', '(651) 774-8445', 'Senior Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Wilson Velasquez' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Michael Patri', c.id, 'PM', '(651) 774-8445', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Patri' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Shadeed Crockett', c.id, 'PM', '(651) 774-8445', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Shadeed Crockett' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Bill Zebro', c.id, 'PM', '(651) 774-8445', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Bill Zebro' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Brian Leitch', c.id, 'PM', '(651) 774-8445', 'Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Brian Leitch' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Michael Sonsalla', c.id, 'PM', '(651) 774-8445', 'Assistant Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Michael Sonsalla' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Ian VanArk', c.id, 'PM', '(651) 774-8445', 'Assistant Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Ian VanArk' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Pam Duckson', c.id, 'PM', '(651) 774-8445', 'Assistant Project Manager', false, 'Saint Paul', 'MN' FROM companies c WHERE c.name='LS Black Constructors' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Pam Duckson' AND company_id=c.id);

-- Shingobee Builders (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Dean Dalzell', c.id, 'PM', '(763) 479-1300', 'Senior Project Manager', false, 'Loretto', 'MN' FROM companies c WHERE c.name='Shingobee Builders' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Dean Dalzell' AND company_id=c.id);

-- Marcus Construction (9)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Eli Gunderson', c.id, 'ESTIMATOR', '(320) 222-6616', 'Construction Estimator', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Eli Gunderson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jesse Ellingson', c.id, 'ESTIMATOR', '(320) 222-6616', 'Construction Estimator', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jesse Ellingson' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Steven Wetterling', c.id, 'PURCHASING', '(320) 222-6616', 'Purchasing Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Steven Wetterling' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Andy Neis', c.id, 'PURCHASING', '(320) 222-6616', 'Procurement Specialist', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Andy Neis' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Micheal Lehner', c.id, 'PM', '(320) 222-6616', 'Project Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Micheal Lehner' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Joe DeGrote', c.id, 'PM', '(320) 222-6616', 'Project Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Joe DeGrote' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Travis Roediger', c.id, 'PM', '(320) 222-6616', 'Project Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Travis Roediger' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Justin Chvala', c.id, 'PM', '(320) 222-6616', 'Project Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Justin Chvala' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Blake Karsch', c.id, 'PM', '(320) 222-6616', 'Assistant Project Manager', false, 'Willmar', 'MN' FROM companies c WHERE c.name='Marcus Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Blake Karsch' AND company_id=c.id);

-- Maertens-Brenny (1)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jacob LeClair', c.id, 'PM', '(763) 350-8762', 'Project Manager', false, 'Brooklyn Park', 'MN' FROM companies c WHERE c.name='Maertens-Brenny' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob LeClair' AND company_id=c.id);

-- Jorgenson Construction (3)
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Alex Rustad', c.id, 'PM', '(763) 784-3877', 'Senior Project Manager', false, 'Blaine', 'MN' FROM companies c WHERE c.name='Jorgenson Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Alex Rustad' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Jacob Bresnahan', c.id, 'PM', '(763) 784-3877', 'Project Manager', false, 'Blaine', 'MN' FROM companies c WHERE c.name='Jorgenson Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Jacob Bresnahan' AND company_id=c.id);
INSERT INTO contacts (name, company_id, role, phone, title, is_decision_maker, city, state) SELECT 'Amanda Ryan', c.id, 'PM', '(763) 784-3877', 'Senior Project Manager', false, 'Blaine', 'MN' FROM companies c WHERE c.name='Jorgenson Construction' AND NOT EXISTS (SELECT 1 FROM contacts WHERE name='Amanda Ryan' AND company_id=c.id);
